/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alcaman
 */
public class jdEditarIngreso extends javax.swing.JDialog {

    String rut = "";
    int numerodocto = 0;
    String tipodocto = "";
    String fecha = "";
    String usuario = "";
     /* Creates new form gdGastoNuevo
     */
    
    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public class ShowListener implements ActionListener {//Listener para checkbox
	public void actionPerformed(ActionEvent e) {
            if(conservar_numero.isSelected()){
                documento_nuevo.setEnabled(false);
                documento_nuevo.setText(String.valueOf(numerodocto));
            }
            else {
                documento_nuevo.setEnabled(true);
                documento_nuevo.setText("");
            }       
	}
    }
    public class ShowListener2 implements ActionListener {//Listener para checkbox
        @Override
        public void actionPerformed(ActionEvent e) {

            if(conservar_fecha.isSelected()){
                FechaTabla.setEnabled(false);
            }
            else {
                FechaTabla.setEnabled(true);
            }       
	}
    }
    
    public jdEditarIngreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conservar_numero.addActionListener(new ShowListener());
        conservar_fecha.addActionListener(new ShowListener2());
        
        documento_nuevo.addKeyListener(new KeyAdapter() {//Limita el campo de texto solo para números
            
            public void keyTyped(KeyEvent e) {
              char c = e.getKeyChar();
              if (!((c >= '0') && (c <= '9') ||
                 (c == KeyEvent.VK_BACK_SPACE) ||
                 (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
              }
            }
          });

        
    }

    //Obtiene los valores necesarios para modificar
    public void SetValues(String rut, int numerodocto, String tipodocto, String fecha){
        this.rut = rut;
        this.numerodocto = numerodocto;
        this.tipodocto = tipodocto;
        this.fecha = fecha;
    }
    //Llena los textfield con los datos actuales
    public void LlenarAntiguos() {
        if(!rut.equals("") && numerodocto!=0 && !tipodocto.equals("") && !fecha.equals("")){
            
            fecha_actual.setText(fecha);
            ingresoactual.setText(String.valueOf(numerodocto));
        }
    }
     
	    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        documento_nuevo = new javax.swing.JTextField();
        FechaTabla = new org.jdesktop.swingx.JXMonthView();
        conservar_numero = new javax.swing.JCheckBox();
        conservar_fecha = new javax.swing.JCheckBox();
        fecha_actual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ingresoactual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nuevo N° Documento:");

        jLabel2.setText("Nueva Fecha: ");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        documento_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documento_nuevoActionPerformed(evt);
            }
        });

        FechaTabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        FechaTabla.setAutoscrolls(true);
        FechaTabla.setTraversable(true);
        FechaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaTablaActionPerformed(evt);
            }
        });

        conservar_numero.setText("Conservar N° Documento");
        conservar_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conservar_numeroActionPerformed(evt);
            }
        });
        conservar_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conservar_numeroKeyPressed(evt);
            }
        });

        conservar_fecha.setText("Conservar Fecha");

        fecha_actual.setFocusable(false);

        jLabel4.setText("Fecha Actual:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(documento_nuevo))
                    .addComponent(jLabel2)
                    .addComponent(FechaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(fecha_actual)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conservar_fecha)
                    .addComponent(conservar_numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(documento_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conservar_numero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conservar_fecha))
                .addGap(18, 18, 18)
                .addComponent(FechaTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setText("Editar Ingreso:");

        ingresoactual.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        ingresoactual.setForeground(new java.awt.Color(255, 0, 0));
        ingresoactual.setText("Ingreso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(ingresoactual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ingresoactual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaTablaActionPerformed

    }//GEN-LAST:event_FechaTablaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int new_numero = 0;
        Date date = null;
        String new_fecha = "";
        if(documento_nuevo.isEnabled() && documento_nuevo.getText().length()>0){//Si texto de nuevo documento está habilitado, se obtiene valor de el.
            new_numero = Integer.parseInt(documento_nuevo.getText().trim());//Se guarda nuevo número
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Se conservará N° Documento.");
        }
        final String NEW_FORMAT = "dd-MM-yyyy";
        if(FechaTabla.isEnabled() || !FechaTabla.isSelectionEmpty()){
            date = FechaTabla.getSelectionDate();
            DateFormat sdf = new SimpleDateFormat(NEW_FORMAT);
            new_fecha = sdf.format(date);//Formato de fecha 
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Se conservará fecha.");
        }
        
        System.out.println(new_numero);
        System.out.println(new_fecha);
        System.out.println(rut);
        ExeSql Sql = new ExeSql();
        ResultSet Rs;

        String fecha_nueva = "";
        int numero_nuevo = 0;

        if(conservar_fecha.isSelected()){//Conserva fecha antigua
            fecha_nueva = fecha;
        }
        else {
            fecha_nueva = new_fecha;//Se asigna fecha nueva
        }
        if(conservar_numero.isSelected()){
            numero_nuevo = numerodocto; // Conserva número antiguo
        }
        else {
            numero_nuevo = new_numero; // Se asigna número nuevo
        }

        String Query;
        Query = "insert into ctacteprvmod (usuario,rut_proveedor,fecha_old,fecha_new,nro_old,nro_new,autorizado,tipdocto,fecha_aut,usuario_aut)"
                + "values ('"+usuario+"',"+rut+",'"+fecha+"','"+fecha_nueva+"',"+numerodocto+","+numero_nuevo+",false,'"+tipodocto+"',now(),'"+usuario+"')";
        try {
            Sql.ExeSql(Query);
            Sql.Commit();
            JOptionPane.showMessageDialog(rootPane,"Se agregó a la tabla de modificaciones.");
        } catch (SQLException ex) {
            Logger.getLogger(jdEditarIngreso.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane,"Ocurrió un error inesperado.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
           
    private void conservar_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conservar_numeroActionPerformed
        
    }//GEN-LAST:event_conservar_numeroActionPerformed

    private void conservar_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conservar_numeroKeyPressed
        
    }//GEN-LAST:event_conservar_numeroKeyPressed

    private void documento_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documento_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documento_nuevoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXMonthView FechaTabla;
    private javax.swing.JCheckBox conservar_fecha;
    private javax.swing.JCheckBox conservar_numero;
    private javax.swing.JTextField documento_nuevo;
    private javax.swing.JTextField fecha_actual;
    private javax.swing.JLabel ingresoactual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
