/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import Utilidades.Exporter;
import Utilidades.POI_excel;
import Utilidades.Utl_Excel;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DavidAlcaman
 */
public class jdOC_OrdenesCompra extends javax.swing.JDialog {
   DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    private Object GrillaOCS;
    public static int pano; 
    public static int pmes;
    public static int pmes_oc;

    /**
     * Creates new form jdTrasnporte
     */
    public jdOC_OrdenesCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla_Det4.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAceptar = new javax.swing.JButton();
        lbmar3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        BtExcel = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        Grilla_Det4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        lbRegDet4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbTotalVtasDet4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btAceptar.setText("Salir");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        lbmar3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbmar3.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0.00");

        BtExcel.setText("Excel");
        BtExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcelActionPerformed(evt);
            }
        });

        Grilla_Det4.setAutoCreateRowSorter(true);
        Grilla_Det4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sku", "Nom", "$ Costo Promedio", "$ Unitario", "Fecha Emision", "Orden", "Margen", "Total Vta", "Rut", "Codigo_oc", "Convenio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla_Det4.getTableHeader().setReorderingAllowed(false);
        Grilla_Det4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla_Det4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Grilla_Det4);
        if (Grilla_Det4.getColumnModel().getColumnCount() > 0) {
            Grilla_Det4.getColumnModel().getColumn(0).setMinWidth(70);
            Grilla_Det4.getColumnModel().getColumn(0).setPreferredWidth(70);
            Grilla_Det4.getColumnModel().getColumn(0).setMaxWidth(70);
            Grilla_Det4.getColumnModel().getColumn(1).setPreferredWidth(100);
            Grilla_Det4.getColumnModel().getColumn(2).setMinWidth(80);
            Grilla_Det4.getColumnModel().getColumn(2).setPreferredWidth(80);
            Grilla_Det4.getColumnModel().getColumn(2).setMaxWidth(80);
            Grilla_Det4.getColumnModel().getColumn(3).setMinWidth(80);
            Grilla_Det4.getColumnModel().getColumn(3).setPreferredWidth(80);
            Grilla_Det4.getColumnModel().getColumn(3).setMaxWidth(80);
            Grilla_Det4.getColumnModel().getColumn(4).setMinWidth(100);
            Grilla_Det4.getColumnModel().getColumn(4).setPreferredWidth(100);
            Grilla_Det4.getColumnModel().getColumn(4).setMaxWidth(100);
            Grilla_Det4.getColumnModel().getColumn(5).setMinWidth(100);
            Grilla_Det4.getColumnModel().getColumn(5).setPreferredWidth(100);
            Grilla_Det4.getColumnModel().getColumn(5).setMaxWidth(100);
            Grilla_Det4.getColumnModel().getColumn(6).setMinWidth(40);
            Grilla_Det4.getColumnModel().getColumn(6).setPreferredWidth(40);
            Grilla_Det4.getColumnModel().getColumn(6).setMaxWidth(40);
            Grilla_Det4.getColumnModel().getColumn(7).setMinWidth(100);
            Grilla_Det4.getColumnModel().getColumn(7).setPreferredWidth(100);
            Grilla_Det4.getColumnModel().getColumn(7).setMaxWidth(100);
            Grilla_Det4.getColumnModel().getColumn(8).setMinWidth(80);
            Grilla_Det4.getColumnModel().getColumn(8).setPreferredWidth(80);
            Grilla_Det4.getColumnModel().getColumn(8).setMaxWidth(80);
            Grilla_Det4.getColumnModel().getColumn(9).setMinWidth(60);
            Grilla_Det4.getColumnModel().getColumn(9).setPreferredWidth(60);
            Grilla_Det4.getColumnModel().getColumn(9).setMaxWidth(60);
            Grilla_Det4.getColumnModel().getColumn(10).setMinWidth(1);
            Grilla_Det4.getColumnModel().getColumn(10).setPreferredWidth(1);
            Grilla_Det4.getColumnModel().getColumn(10).setMaxWidth(1);
        }

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Nro Registros:");

        lbRegDet4.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Total Ventas");

        lbTotalVtasDet4.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtExcel)
                        .addGap(65, 65, 65)
                        .addComponent(btAceptar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbRegDet4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotalVtasDet4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbmar3)
                        .addGap(62, 62, 62)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbRegDet4)
                            .addComponent(jLabel14)
                            .addComponent(lbTotalVtasDet4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtExcel)
                            .addComponent(btAceptar))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lbmar3))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void CargaOC(int agno, int mes, int mes_oc  ){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Det4.getModel();
        pano = agno;
        pmes = mes; 
        pmes_oc = mes_oc;
        
        
        double Sumador = 0.00;
        
           lblTotal.setText(String.valueOf(fmMain.FormatoNumero(Sumador)));      
        
        int ContReg=0;
         while(TableModel.getRowCount()>0)
             TableModel.removeRow(0);
        try {
            
            String Query ="select ALL_OC.codigo, ALL_OC.convenio,sum(ALL_OC.sum_oc) sum_oc\n" +
"FROM\n" +
"(select \n" +
"conv.codigo, conv.convenio,c.rut,c.codigo_oc,c.orden,\n" +
"SUM(d.cantidad * d.valorunitario) sum_oc\n" +
"          from occh c\n" +
"         left join occhdet d on c.rut = d.rut and \n" +
"          c.orden = d.orden \n" +
"          and  c.codigo_oc   = d.codigo_oc\n" +
"     left join producto p on d.sku = p.sku\n" +
"     left join par_convenio conv on conv.codigo = p.convenio\n" +
"          where \n" +
"          extract(year from c.femision) =" + agno + " and \n" +
"          extract(month from c.femision) =" + mes_oc + " and \n" +
"          conv.convenio is  not null\n" +
"group by \n" +
"conv.codigo, conv.convenio,c.rut,c.codigo_oc,c.orden) ALL_OC\n" +
"Left join (SELECT  \n" +
"                         conv.codigo, conv.convenio,\n" +
"                         c.rut, c.codigo_oc , c.occh, \n" +
"                          SUM(d.cantidad * d.valorunitario) sum_fac\n" +
"					from ctactecli c\n" +
"                       left join ctacteclidet d on c.rut = d.rut and c.tipdocto =\n" +
"                        d.tipdocto and c.nrodocto = d.nrodocto\n" +
"                       left join producto p on d.sku = p.sku\n" +
"                       left join par_convenio conv on conv.codigo = p.convenio\n" +
"                       inner join \n" +
"                       (\n" +
"                         select distinct orden,\n" +
"                                codigo_oc\n" +
"                         from occh  where \n" +
"          extract(year from femision) =" + agno + " and \n" +
"          extract(month from femision) =" + mes_oc + " \n" +
"                       ) oc on c.occh = oc.orden and c.codigo_oc = oc.codigo_oc\n" +
"                  where c.tipdocto in ('NCC','FAC','FEC') and\n" +
"                       extract(year from c.femision) = " + agno + " and \n" +
"                       extract(month from c.femision) BETWEEN 1 and " + mes + " and\n" +
"                   conv.convenio is not null\n" +
"                  group by  \n" +
"					conv.codigo, conv.convenio,c.rut, c.codigo_oc , c.occh) ALL_FAC \n" +
"on \n" +
"		ALL_FAC.rut  = all_oc.rut and\n" +
"		ALL_FAC.codigo_oc  = all_oc.codigo_oc and\n" +
"        ALL_FAC.occh  = all_oc.orden and\n" +
"        ALL_FAC.codigo  = all_oc.codigo \n" +
"    where ALL_FAC.rut is NULL\n" +
"group by ALL_OC.codigo, ALL_OC.convenio   order by ALL_OC.codigo  ";
            
            Rs = Sql.Select(Query);
            
            
            Rs.last(); 
            int numRows = Rs.getRow(); 
            Rs.beforeFirst(); // esto te lo deja como al principio 
            System.out.print(numRows);
            
            
            
            while (Rs.next()){
                ContReg++;
                        TableModel.addRow(new Object[]{
                                               Rs.getString("codigo").trim(),
                                               Rs.getString("convenio").trim(), 
                                               fmMain.FormatoNumero(Rs.getDouble("sum_oc"))});
                        
                        
                        
                        
                Sumador = Sumador + Rs.getDouble("sum_oc");
                lblTotal.setText(String.valueOf(fmMain.FormatoNumero(Sumador)));
               }
                
               // Grilla_OC.changeSelection(0, 0 , false, false);
            
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
            
        }
        
    }   
    
    
    
     public void CargaDetMargenOrdenes(String  ano, String mes){
        ExeSql Sql = new ExeSql();
        ResultSet Rs10;
       //String  Query = " ";
        DefaultTableModel TableModel = (DefaultTableModel) Grilla_Det4.getModel();
        double Sumador=0;
        int ContReg=0;
      
//limpiaTablaEncabezadoOrdenesDet();
      while(TableModel.getRowCount()>0)
             TableModel.removeRow(0);
        try {
                
                        String Query = "   select \n" +
                        "   				  conv.convenio,\n" +
                        "   				  conv.codigo,\n" +
                        "   				  d.sku,\n" +
                        "                   p.nombre,\n" +
                        "                   d.valorunitario,\n" +        
                        "                   p.valultcompra,\n" +
                        "                   p.costopromedio,\n" +
                        "                   c.femision,\n" +
                        "                   c.codigo_oc || '-' || c.orden orden, \n" +
                        "                  ((d.valorunitario - p.costopromedio) / d.valorunitario) * 100 as Margen,\n" +
                        "          	   cast((sum(d.cantidad)) * d.valorunitario as integer) as totalVta,\n" +
                        "                   c.rut, c.codigo_oc \n" +        
                        "         from occh c\n" +
                        "         left join occhdet d on c.rut = d.rut and \n" +
                        "          c.orden = d.orden \n" +
                        "          and  c.codigo_oc   = d.codigo_oc\n" +
                        "     left join producto p on d.sku = p.sku\n" +
                        "     left join par_convenio conv on conv.codigo = p.convenio\n" +
                        "          where \n" +
                        "          extract(year from c.femision) =" + ano.toString() + " and \n" +
                        "          extract(month from c.femision) =" + mes.toString() + " and \n"+
                        "          conv.convenio is  not null\n" +
                        "          group by conv.codigo,conv.convenio,\n" +
                        "                   d.sku,\n" +
                        "                   p.nombre,\n" +
                        "                   p.valultcompra,\n" +
                        "                   d.valorunitario,\n" +
                        "                   p.costopromedio,\n" +
                        "                   c.femision,\n" +
                        "                   c.orden,c.rut, c.codigo_oc\n";
           
        
            
            Rs10 = Sql.Select(Query );
                while(TableModel.getRowCount()>0)
                    TableModel.removeRow(0);
            while (Rs10.next()){
                ContReg++;
                
                        
                        TableModel.addRow(new Object[]{
                                               Rs10.getString("sku").trim(),
                                               Rs10.getString("nombre").trim(), 
                                               fmMain.FormatoNumero(Rs10.getDouble("costopromedio")),
                                               fmMain.FormatoNumero(Rs10.getDouble("valorunitario")),
                                               Rs10.getString("femision").trim(), 
                                               Rs10.getString("orden").trim(), 
                                               fmMain.FormatoTotal(Rs10.getDouble("Margen")),
                                               Rs10.getString("totalVta").trim(),
                                               fmMain.FormatoTotal(Rs10.getDouble("Rut")),
                                               fmMain.FormatoTotal(Rs10.getInt("codigo_oc")),
                                               Rs10.getString("convenio").trim()});
                Sumador = Sumador + Rs10.getDouble("totalVta");
                
                
                System.out.print(TableModel.getRowCount());
               }
         
            if (ContReg >0) {
                 Grilla_Det4.changeSelection(0, 0 , false, false);
            }
             
            lbTotalVtasDet4.setText(fmMain.FormatoNumero(Sumador));
            lbRegDet4.setText(fmMain.FormatoTotal(ContReg));

          
        } catch (Exception e) {
          
        } finally{
            Sql.Close();
        }
        
    }
    
    public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(jdOC_OrdenesCompra.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
    
    
    
    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void BtExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcelActionPerformed
        // TODO add your handling code here:
        
//        if(Grilla.getRowCount()==0){
//            fmMain.Mensaje("Nada que exportar");
//            return;
//        }
//
//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);
//
//        if(chooser.showSaveDialog(null)== JFileChooser.APPROVE_OPTION){
//            List<JTable> tb=new ArrayList<>();
//            List<String> nom=new ArrayList<>();
//            tb.add(Grilla);
//            nom.add("Año: " + pano + " Mes: " + pmes + " Mes_OC: "+ pmes_oc);
//            String file=chooser.getSelectedFile().toString().concat(".xls");
//            try {
//                Exporter e = new Exporter(new File(file), tb, nom);
//                
//                if(e.export())
//                fmMain.Mensaje("Datos Exportados");
//                abrir(file);
//                
//            } catch (Exception e) {
//                fmMain.Mensaje(e.getMessage());
//            }
//
//           
//        }
        
        
        if(Grilla_Det4.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);


            List<JTable> tb=new ArrayList<>();
            List<String> nom=new ArrayList<>();
            tb.add(Grilla_Det4);
            nom.add("Agno->" + pano + " Mes->" + pmes + " Mes_OC->"+ pmes_oc);
            
            File folder = new File("c:/temp");
            if (!folder.exists())
            {
                folder.mkdir();
            }
            
             String file = "C:/temp/convenio" + pano + "-" + pmes + "-"+ pmes_oc +".xls";       
            
            
            try {
                Exporter e = new Exporter(new File(file), tb, nom);
                
                if(e.export())
                //fmMain.Mensaje("Datos Exportados");
                   //abrir(file);
                Utl_Excel.Abrir_Doc(file);
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }
    }//GEN-LAST:event_BtExcelActionPerformed

    private void Grilla_Det4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla_Det4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Grilla_Det4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdOC_OrdenesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdOC_OrdenesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdOC_OrdenesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdOC_OrdenesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdOC_OrdenesCompra dialog = new jdOC_OrdenesCompra(new javax.swing.JFrame(), true);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExcel;
    private javax.swing.JTable Grilla_Det4;
    private javax.swing.JButton btAceptar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbRegDet4;
    private javax.swing.JLabel lbTotalVtasDet4;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbmar3;
    // End of variables declaration//GEN-END:variables
}
