/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import Formularios.fmMain;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alcaman
 */
public class jdPagarPrv extends javax.swing.JDialog {
    int Tipo;
    String Cuenta;
    /**
     * Creates new form jdPagarPrv
     */
    public jdPagarPrv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Tipo=-99;
        initComponents();
        CargaTipoPago();
        CargaBancos();
        cbBancoId.setVisible(false);
        cbBanco.setVisible(false);
        jLabel11.setVisible(false);
        cbFormaPagoId.setVisible(false);
        lbPagado.setVisible(false);
        lbPagadoFecha.setVisible(false);
        Tipo=0;
        dtFechaPago.setDate(null);
        btIr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNroFAP = new javax.swing.JTextField();
        txFechaFAP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txTotalFAP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txSaldo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txFechaVenc = new javax.swing.JTextField();
        txMontoPago = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txNroPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbFormaPago = new javax.swing.JComboBox();
        cbFormaPagoId = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txNroCuota = new javax.swing.JTextField();
        cbBancoId = new javax.swing.JComboBox();
        cbBanco = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        lbPagado = new javax.swing.JLabel();
        lbPagadoFecha = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dtFechaPago = new org.jdesktop.swingx.JXDatePicker();
        btIr = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txDv = new javax.swing.JTextField();
        txNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btPagar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Factura"));

        jLabel3.setText("Número");

        jLabel4.setText("Fecha");

        txNroFAP.setEditable(false);

        txFechaFAP.setEditable(false);

        jLabel9.setText("Total factura");

        txTotalFAP.setEditable(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Saldo Factura");

        txSaldo.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txTotalFAP)
                    .addComponent(txFechaFAP)
                    .addComponent(txNroFAP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txSaldo))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNroFAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txFechaFAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txTotalFAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pago"));

        jLabel5.setText("Vencimiento");

        txFechaVenc.setEditable(false);
        txFechaVenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFechaVencActionPerformed(evt);
            }
        });

        jLabel6.setText("Monto");

        jLabel7.setText("Forma de Pago");

        txNroPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txNroPagoFocusLost(evt);
            }
        });
        txNroPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNroPagoActionPerformed(evt);
            }
        });

        jLabel8.setText("Nro Documento");

        cbFormaPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaPagoActionPerformed(evt);
            }
        });

        cbFormaPagoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFormaPagoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaPagoIdActionPerformed(evt);
            }
        });

        jLabel10.setText("Cuota");

        cbBancoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBancoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBancoIdActionPerformed(evt);
            }
        });

        cbBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBancoActionPerformed(evt);
            }
        });

        jLabel11.setText("Banco");

        lbPagado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPagado.setForeground(new java.awt.Color(0, 102, 0));
        lbPagado.setText("PAGADO");

        lbPagadoFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPagadoFecha.setForeground(new java.awt.Color(0, 102, 0));
        lbPagadoFecha.setText("2015-08-01");

        jLabel12.setText("Fecha de Pago");

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNroPago)
                    .addComponent(dtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFormaPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txNroCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFormaPagoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPagado)
                            .addComponent(lbPagadoFecha))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txNroCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbBancoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbPagado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPagadoFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbFormaPagoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txNroPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Proveedor"));

        txDv.setEditable(false);

        txNombre.setEditable(false);

        jLabel1.setText("Rut");

        txRut.setEditable(false);

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPagar.setText("Pagar");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPagar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btPagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void CargaPagado(String Pago){
     ExeSql Sql = new ExeSql();
        ResultSet Rs;
       
        try {
            Rs = Sql.Select("select p.rut,p.dv,p.nombre,fp.nrodocto,fp.femision,fp.totaldocto ,pp.nrocuota || ' de ' || fp.cuotas as cuotas,\n" +
                            "pp.fpago,pp.monto,pa.tipopago,CAST(pa.fecha as date) as fechapago,pa.banco,pa.nrodocumento\n" +
                            "from prv_cuentasxpagar pp\n" +
                            "left join proveedor p on pp.rut=p.rut\n" +
                            "left join ctacteprv fp on fp.rut=pp.rut and fp.tipdocto=pp.tipdocto and fp.nrodocto=pp.nrodocto\n" +
                            "left join prv_pagos pa on pa.cuenta = pp.id \n" +
                            "where pp.id=" + Pago);
            Rs.next();
            
            txRut.setText(Rs.getString("Rut").trim());
            txDv.setText(Rs.getString("dv").trim());
            txNombre.setText(Rs.getString("Nombre").trim());
            txNroFAP.setText(Rs.getString("NroDocto").trim());
            txFechaFAP.setText(Rs.getString("femision").trim());
            txTotalFAP.setText(Rs.getString("totaldocto").trim());
            txNroCuota.setText(Rs.getString("Cuotas").trim());
            txFechaVenc.setText(Rs.getString("fpago").trim());
            txMontoPago.setText(Rs.getString("monto").trim());
            cbFormaPagoId.setSelectedItem(Rs.getString("tipopago"));
            lbPagadoFecha.setText(Rs.getString("fechapago").trim());
            cbBancoId.setSelectedItem(Rs.getString("banco"));
            txNroPago.setText(Rs.getString("nrodocumento"));
            
            lbPagado.setVisible(true);
            lbPagadoFecha.setVisible(true);
            btPagar.setVisible(false);
            txNroPago.setEditable(false);
            
            
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }   
        
        
    }
    public String getFechaPago() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return( sdf.format( (dtFechaPago.getDate()).getTime() ) );
        } catch (Exception e) {
            return "";
        }
        
    }
    public void CargaPago(String Pago){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        Cuenta = Pago;
        
        try {
            Rs = Sql.Select("select p.rut,p.dv,p.nombre,fp.nrodocto,fp.femision,fp.totaldocto ,pp.nrocuota || ' de ' || fp.cuotas as cuotas,\n" +
                            "pp.fpago,pp.monto - pp.pagado as monto,pp.tipopago\n" +
                            "from prv_cuentasxpagar pp\n" +
                            "left join proveedor p on pp.rut=p.rut\n" +
                            "left join ctacteprv fp on fp.rut=pp.rut and fp.tipdocto=pp.tipdocto and fp.nrodocto=pp.nrodocto\n" +
                            "where pp.id=" + Pago);
            Rs.next();
            
            txRut.setText(Rs.getString("Rut").trim());
            txDv.setText(Rs.getString("dv").trim());
            txNombre.setText(Rs.getString("Nombre").trim());
            txNroFAP.setText(Rs.getString("NroDocto").trim());
            txFechaFAP.setText(Rs.getString("femision").trim());
            txTotalFAP.setText(Rs.getString("totaldocto").trim());
            txNroCuota.setText(Rs.getString("Cuotas").trim());
            txFechaVenc.setText(Rs.getString("fpago").trim());
            txMontoPago.setText(Rs.getString("monto").trim());
            txSaldo.setText(Rs.getString("monto").trim());
            cbFormaPagoId.setSelectedItem(Rs.getString("tipopago"));
            
            
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }
            
        
    }
    private void CargaTipoPago(){
        
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
    
        cbFormaPago.removeAllItems();
        cbFormaPagoId.removeAllItems();
    
        try {
            Rs = Sql.Select("select codigo,nombre\n" +
                            "from par_general \n" +
                            "where tipo='TIPOPAGOPRV'\n" +
                            "and codigo IN ('4') \n" +
                            "and vigente=1\n" +
                            "order by codigo");
            
            while(Rs.next()){
                
                cbFormaPago.addItem(Rs.getString("nombre"));
                cbFormaPagoId.addItem(Rs.getString("codigo"));
            }
        
        }catch (Exception e) {
            
            fmMain.Mensaje(e.getMessage());
        
        }finally{
            Sql.Close();
        }
    }
    
//------------------------------------------------------------------------------
// Carga BANCOS
//------------------------------------------------------------------------------
    private void CargaBancos(){
        ExeSql  Sql = new ExeSql();
        ResultSet Rs;

        cbBanco.removeAllItems();
        cbBancoId.removeAllItems();

        try {
            Rs = Sql.Select("select codigo, banco\n" +
                    "from par_banco\n" +
                    "order by codigo asc ");
            while(Rs.next()){
                cbBanco.addItem(Rs.getString("banco"));
                cbBancoId.addItem(Rs.getString("codigo"));
                
            }
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
        }finally{
            Sql.Close();
        }

    }
    public Integer GetPagado(){
        return Tipo;
    }
    
    private boolean ExisteNCP(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        try {
            Rs = Sql.Select("select count(*) as Existe\n" +
                            "from ctacteprv\n" +
                            "where tipdocto='NCP'\n" +
                            "and nrodocto="+ txNroPago.getText().trim() +"\n" +
                            "and rut=" + txRut.getText().trim());
            Rs.next();
            if(Rs.getInt("Existe")==0)
                return false;
            else
                return true;
                
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
            return false;
        } finally{
            Sql.Close();
        }
            
    }
    private String CupoNCP(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        
        try {
            Rs = Sql.Select("select totaldocto - pagado as cupo\n" +
                            "from ctacteprv\n" +
                            "where tipdocto='NCP'\n" +
                            "and nrodocto="+ txNroPago.getText().trim() +"\n" +
                            "and rut=" + txRut.getText().trim());
            Rs.next();
            
            System.out.println("EL cupo ES : "+Rs.getString("cupo"));
            return  Rs.getString("cupo");
                
        } catch (Exception e) {
            fmMain.Mensaje(e.getMessage());
            return "0";
        } finally{
            Sql.Close();
        }
    }
    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        
        ExeSql Sql2 = new ExeSql();
        ExeSql Sql3 = new ExeSql();
        ResultSet Rs2;
        
        
        //Validación
        if(getFechaPago().isEmpty()){
            fmMain.Mensaje("Debe especificar la fecha de pago");
            return;
        }

        
        double montodoc = Double.parseDouble(txSaldo.getText().toString().trim());
        double montopago = Double.parseDouble(txMontoPago.getText().toString().trim());
        
        
        if (montopago > montodoc){
        
            fmMain.Mensaje("El Monto es Mayor que el valor del Documento!");
            return;
        
        }
       
        
        
        if (!cbFormaPagoId.getSelectedItem().toString().trim().equals("4")){
        
        
            fmMain.Mensaje("Tipo de Pago autorizado : NOTA CREDITO");
            return;
        
        
        }
        
        
        if(fmMain.OkCancel("¿Desea dar por pagada la cuota?")== JOptionPane.OK_OPTION){
            ExeSql Sql = new ExeSql();
            
            try {
                
                Sql.ExeSql("insert into prv_pagos\n" +
                        "(cuenta,tipopago,banco,monto,nrodocumento,fechapago)\n" +
                        "values\n" +
                        "("+ Cuenta +","+ cbFormaPagoId.getSelectedItem().toString().trim() +","+ cbBancoId.getSelectedItem().toString().trim() +"," + txMontoPago.getText().trim() +"," + txNroPago.getText().trim()+",'" + getFechaPago() + "')");
                Sql.Commit();
               
                
                 System.out.println("LA FORMA DE PAGO ES "+cbFormaPagoId.getSelectedItem().toString().trim());
                
                if (cbFormaPagoId.getSelectedItem().toString().trim().equals("4")){   //NOTA DE CREDITO
                
                    System.out.println("ENTRA AQUI");
                    
                    
                    Rs2 = Sql2.Select("select nrodocto, autoriza,totaldocto\n" +
                                      "from ctacteprv\n" +
                                      "where tipdocto IN ('NCP') \n" +
                                      "and nrodocto="+ txNroPago.getText().trim() +"\n" +
                                      "and autoriza = 1 OR autoriza = 2 \n" +               //ingresada en recepcion (0) y autorizada por Jack
                                      "and rut=" + txRut.getText().trim());
                    
                    if (Sql2.GetRowCount() > 0){
                    
                        Rs2.next();
                        
                        double MontoPago = Double.parseDouble(txMontoPago.getText().trim());
                        double totaldocto = Rs2.getDouble("totaldocto");
                        int autoriza = 1;
                        
                        if (MontoPago < totaldocto){
                        
                            autoriza = 2;    //pago parcial
                        
                        
                        }else if (MontoPago == totaldocto) {
                        
                            autoriza = 3;       //pago total
                        
                        }
                        
                                                
                        Sql3.ExeSql("UPDATE ctacteprv SET \n" +
                                   "autoriza = "+autoriza+" \n" +             
                                   "where tipdocto IN ('NCP') \n" +
                                   "and nrodocto="+ txNroPago.getText().trim() +"\n" +
                                   "and autoriza = 1 OR autoriza = 2 \n" +
                                   "and rut=" + txRut.getText().trim());
                        
                        Sql3.Commit();
                    
                    }else if (Sql2.GetRowCount() == 0) {
                    
                    
                        fmMain.Mensaje("La Nota de Crédito ya fue Ocupada!");
                        return;
                    
                    }
                    
                }
                
                
                JOptionPane.showMessageDialog(null,"Pagado");
                Tipo=1;
                dispose();
            } catch (SQLException | HeadlessException e) {
                    Sql.Rollback();
                    Sql3.Rollback();
                    fmMain.Mensaje(e.getMessage());
            
            }finally{
                Sql3.Close();
                Sql.Close();
            }
        }
        
        
        
        
    }//GEN-LAST:event_btPagarActionPerformed

    private void txFechaVencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFechaVencActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFechaVencActionPerformed

    private void cbFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagoActionPerformed
        if (Tipo != -99) {
            cbFormaPagoId.setSelectedIndex(cbFormaPago.getSelectedIndex());

//            if (cbFormaPago.getSelectedItem().toString().toUpperCase().equals("CHEQUE")) {
//                txNroPago.setText("");
//                txNroPago.setEditable(false);
//                btIr.setVisible(true);
//                cbBanco.setEnabled(false);
//
//            } else {
//                txNroPago.setEditable(true);
//                btIr.setVisible(false);
//                cbBanco.setEnabled(true);
//            }
            
              txNroPago.setEditable(true);
              btIr.setVisible(false);
              cbBanco.setEnabled(true);
            
        }

    }//GEN-LAST:event_cbFormaPagoActionPerformed

    private void cbFormaPagoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagoIdActionPerformed
        if(Tipo!=-99){
            cbFormaPago.setSelectedIndex(cbFormaPagoId.getSelectedIndex());
        
        }
        
            
    }//GEN-LAST:event_cbFormaPagoIdActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbBancoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBancoIdActionPerformed
        if(Tipo!=-99)
            cbBanco.setSelectedIndex(cbBancoId.getSelectedIndex());// TODO add your handling code here:
    }//GEN-LAST:event_cbBancoIdActionPerformed

    private void cbBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBancoActionPerformed
        if(Tipo!=-99){
            cbBancoId.setSelectedIndex(cbBanco.getSelectedIndex());
        }
            
    }//GEN-LAST:event_cbBancoActionPerformed

    private void txNroPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNroPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNroPagoActionPerformed

    private void txNroPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNroPagoFocusLost
        if(cbFormaPagoId.getSelectedItem().toString().equals("4") && !txNroPago.getText().isEmpty()){
            if(!ExisteNCP())
                fmMain.Mensaje("Nota de Credito no encontrada");
            else
                txMontoPago.setText(CupoNCP());
        }
    }//GEN-LAST:event_txNroPagoFocusLost

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
        
        jdGetCheque Cheque = new jdGetCheque(null, true);
        if(Cheque.CargaDocumentos(txRut.getText().trim())){
            Cheque.setLocationRelativeTo(null);
            Cheque.setVisible(true);
            cbBancoId.setSelectedItem(Cheque.GetBanco());
            txNroPago.setText(Cheque.GetDocumento());
        }
        else{
            fmMain.Mensaje("No existen cheques para elrut: " + txRut.getText());
            Cheque.dispose();
        }
        
    }//GEN-LAST:event_btIrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdPagarPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdPagarPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdPagarPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdPagarPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdPagarPrv dialog = new jdPagarPrv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btPagar;
    private javax.swing.JComboBox cbBanco;
    private javax.swing.JComboBox cbBancoId;
    private javax.swing.JComboBox cbFormaPago;
    private javax.swing.JComboBox cbFormaPagoId;
    private org.jdesktop.swingx.JXDatePicker dtFechaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbPagado;
    private javax.swing.JLabel lbPagadoFecha;
    private javax.swing.JTextField txDv;
    private javax.swing.JTextField txFechaFAP;
    private javax.swing.JTextField txFechaVenc;
    private javax.swing.JTextField txMontoPago;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txNroCuota;
    private javax.swing.JTextField txNroFAP;
    private javax.swing.JTextField txNroPago;
    private javax.swing.JTextField txRut;
    private javax.swing.JTextField txSaldo;
    private javax.swing.JTextField txTotalFAP;
    // End of variables declaration//GEN-END:variables
}
