/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class jdProductosAsociadosPrv extends javax.swing.JDialog {

    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    public static String CodigoSel;
    public static String CostoSel;
    
    public jdProductosAsociadosPrv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        GrillaOtros.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        GrillaOtros.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        GrillaOtros.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        GrillaOtros.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        GrillaOtros.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        GrillaOtros.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        GrillaOtros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GrillaOtros.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        GrillaOtros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Unidad", "P.Compra", "Stock", "OCP", "OCC", "VTA 3M", "OCC 3M"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaOtros.setToolTipText("Ordenes de Compra");
        GrillaOtros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GrillaOtrosMouseMoved(evt);
            }
        });
        GrillaOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaOtrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrillaOtrosMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(GrillaOtros);
        if (GrillaOtros.getColumnModel().getColumnCount() > 0) {
            GrillaOtros.getColumnModel().getColumn(0).setMinWidth(75);
            GrillaOtros.getColumnModel().getColumn(0).setPreferredWidth(75);
            GrillaOtros.getColumnModel().getColumn(0).setMaxWidth(75);
            GrillaOtros.getColumnModel().getColumn(1).setMinWidth(350);
            GrillaOtros.getColumnModel().getColumn(1).setPreferredWidth(350);
            GrillaOtros.getColumnModel().getColumn(2).setMinWidth(75);
            GrillaOtros.getColumnModel().getColumn(2).setPreferredWidth(75);
            GrillaOtros.getColumnModel().getColumn(2).setMaxWidth(75);
            GrillaOtros.getColumnModel().getColumn(4).setMinWidth(75);
            GrillaOtros.getColumnModel().getColumn(4).setPreferredWidth(75);
            GrillaOtros.getColumnModel().getColumn(4).setMaxWidth(75);
            GrillaOtros.getColumnModel().getColumn(5).setMinWidth(75);
            GrillaOtros.getColumnModel().getColumn(5).setPreferredWidth(75);
            GrillaOtros.getColumnModel().getColumn(5).setMaxWidth(75);
            GrillaOtros.getColumnModel().getColumn(6).setMinWidth(75);
            GrillaOtros.getColumnModel().getColumn(6).setPreferredWidth(75);
            GrillaOtros.getColumnModel().getColumn(6).setMaxWidth(75);
            GrillaOtros.getColumnModel().getColumn(7).setMinWidth(80);
            GrillaOtros.getColumnModel().getColumn(7).setPreferredWidth(80);
            GrillaOtros.getColumnModel().getColumn(7).setMaxWidth(80);
            GrillaOtros.getColumnModel().getColumn(8).setMinWidth(80);
            GrillaOtros.getColumnModel().getColumn(8).setPreferredWidth(80);
            GrillaOtros.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrillaOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaOtrosMouseClicked
        if(evt.getClickCount()==2){
            CodigoSel = GrillaOtros.getValueAt(GrillaOtros.getSelectedRow(),0).toString().trim();
            CostoSel = GrillaOtros.getValueAt(GrillaOtros.getSelectedRow(),3).toString().trim();
            dispose();
        }
    }//GEN-LAST:event_GrillaOtrosMouseClicked

    private void GrillaOtrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaOtrosMouseEntered
        
    }//GEN-LAST:event_GrillaOtrosMouseEntered

    private void GrillaOtrosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaOtrosMouseMoved
        int Col = GrillaOtros.columnAtPoint(evt.getPoint());
        
        if(Col==3)
            GrillaOtros.setToolTipText("Precio de Compra");
        else if(Col==4)
            GrillaOtros.setToolTipText("Stock en Bodega");
        else if(Col==5)
            GrillaOtros.setToolTipText("Ordenes a Proveedor");
        else if(Col==6)
            GrillaOtros.setToolTipText("Ordenes de Clientes");
        else if(Col==7)
            GrillaOtros.setToolTipText("<html>Unidades vendidas <br> en los ultimos <br>3 meses</html>");
        else if(Col==8)
            GrillaOtros.setToolTipText("<html>Ordenes de Clientes <br> recibidas en <br> ultimos 3 meses </html>");
        else
            GrillaOtros.setToolTipText("");
    }//GEN-LAST:event_GrillaOtrosMouseMoved
    public String GetCodigoSelect(){
        return CodigoSel;
    }
    public String GetCostoSelect(){
        return CostoSel;
    }
    public void Show(String Rut, String Agregados){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel TableModel3 = (DefaultTableModel) GrillaOtros.getModel();
        
        while(TableModel3.getRowCount()>0)
              TableModel3.removeRow(0);
        
        CodigoSel = "";
        
        try {
            Rs = Sql.Select("select p.sku,p.nombre,u.unidad,i.stock,i.ocp,i.occ,sum(cd.cantidad) as cant,count(cd.*) as cont,p.valultcompra\n" +
                            "from producto p\n" +
                            "left join par_unidad u on p.unidad=u.codigo\n" +
                            "left join inventario i on p.sku=i.sku\n" +
                            "left join ctacteclidet cd on i.sku=cd.sku and cd.tipdocto='FAC'\n" +
                            "left join ctactecli cc on cd.rut=cc.rut and cd.nrodocto=cc.nrodocto and cd.tipdocto=cc.tipdocto and cc.femision> current_date - 90\n" +
                            "where p.rutultprv = " + Rut + "\n" +
                            "and cc.femision is not null\n" +
                            "and p.sku not in ("+ Agregados +")\n" +
                            "group by p.sku,p.nombre,u.unidad,i.stock,i.ocp,i.occ,p.valultcompra\n" +
                            "order by cant desc");
            while(Rs.next()){
            TableModel3.addRow(new Object[]{    Rs.getString("sku").trim(), 
                                                    Rs.getString("nombre").trim(), 
                                                    Rs.getString("unidad").trim(),
                                                    Rs.getDouble("valultcompra"),
                                                    Rs.getInt("stock"),
                                                    Rs.getInt("ocp"),
                                                    Rs.getInt("occ"),
                                                    Rs.getDouble("cant"),
                                                    Rs.getDouble("cont")
                                             });
            }
         GrillaOtros.setDefaultRenderer(Object.class, new Utilidades.TableCellRendererColor_1());
         GrillaOtros.repaint();
         this.setVisible(true);
        } catch (Exception e) {
        }finally{
            Sql.Close();
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdProductosAsociadosPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdProductosAsociadosPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdProductosAsociadosPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdProductosAsociadosPrv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdProductosAsociadosPrv dialog = new jdProductosAsociadosPrv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaOtros;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
