/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.ExeSql;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author infornatica
 */
public class jdSeparablesIngreso extends javax.swing.JDialog {

    /**
     * Creates new form jdSeparablesIngreso
     */
    public jdSeparablesIngreso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton1.doClick();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_Copiar = new javax.swing.JPopupMenu();
        jDescripcion2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txSku = new javax.swing.JTextField();
        lbcargando = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        radio_ingreso = new javax.swing.JRadioButton();
        radio_pendientes = new javax.swing.JRadioButton();

        jDescripcion2.setText("Copiar Orden");
        jDescripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescripcion2ActionPerformed(evt);
            }
        });
        jPopupMenu_Copiar.add(jDescripcion2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Orden", "SKU", "Cantidad", "Separado", "Despachado", "Ingreso Cant.", "Diferencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setComponentPopupMenu(jPopupMenu_Copiar);
        Grilla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(80);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(150);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(200);
            Grilla.getColumnModel().getColumn(1).setMinWidth(80);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(120);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(150);
            Grilla.getColumnModel().getColumn(2).setMinWidth(30);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(3).setMinWidth(30);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(4).setMinWidth(30);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(5).setMinWidth(30);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(6).setMinWidth(30);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FILTRO TABLA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        jLabel11.setText("FILTRO:");

        txSku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSkuActionPerformed(evt);
            }
        });
        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSkuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSkuKeyTyped(evt);
            }
        });

        lbcargando.setText("Cargando");
        lbcargando.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Actualiza.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_ingreso);
        radio_ingreso.setSelected(true);
        radio_ingreso.setText("Completables solo con cantidad en ingreso");
        radio_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_ingresoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_pendientes);
        radio_pendientes.setText("Ordenes con productos pendientes en ingreso");
        radio_pendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSku, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radio_ingreso)
                        .addGap(18, 18, 18)
                        .addComponent(radio_pendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbcargando)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbcargando)
                        .addComponent(radio_ingreso)
                        .addComponent(radio_pendientes)))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void CargaIngreso() {
        ExeSql exe = new ExeSql();
        ResultSet rs = null;
        String query = "select resultado_2.orden, oc.sku, resultado_2.result,\n" +
                        "oc.cantidad, oc.separado, oc.despachado, \n" +
                        "case when resultado_2.result in (2,3) \n" +
                        "then (select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1')\n" +
                        "else 0\n" +
                        "end as cant_ingre,\n" +
                        "case when (select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1') < (oc.cantidad - oc.separado) and\n" +
                        "			(select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1') > 0 then \n" +
                        "			 (select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1') \n" +
                        "    when (select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1') > (oc.cantidad - oc.separado) \n" +
                        "    	and (select sum(cant) from mt_productos where sku = oc.sku and ubicacion = 'TRAN.1001.1') > 0\n" +
                        "        then (oc.cantidad - oc.separado)\n" +
                        "	end as diferencia\n" +
                        "\n" +
                        "from \n" +
                        "(select CAST(resultado.codigo_oc as varchar) || '-' || resultado.orden orden, sum(distinct resultado.estado) result\n" +
                        "from\n" +
                        "(select sku_.codigo_oc, sku_.orden, o.sku,  \n" +
                        "o.cantidad, o.separado, o.despachado, mt.cant,           \n" +
                        "case when o.cantidad < mt.cant \n" +
                        "	and mt.cant > 0 \n" +
                        "    and o.separado >= 0 \n" +
                        "    and (o.cantidad > (o.separado+o.despachado)) \n" +
                        "    then 2 /**Se puede**/\n" +
                        "    else 1 /**No se puede**/\n" +
                        "    end as estado,\n" +
                        "case when mt.cant > 0 then 'Tiene stock en ingreso' else 'No tiene stock en ingreso' end as ingreso\n" +
                        "from (select codigo_oc, orden from occhdet ) sku_\n" +
                        "left join occhdet o on o.codigo_oc = sku_.codigo_oc and o.orden = sku_.orden\n" +
                        "left join mt_productos mt on mt.sku = o.sku and mt.ubicacion = 'TRAN.1001.1') resultado\n" +
                        "group by resultado.codigo_oc, resultado.orden)\n" +
                        "resultado_2\n" +
                        "left join occhdet oc on CAST(oc.codigo_oc as varchar) || '-' || oc.orden in (resultado_2.orden)\n" +
                        "\n" +
                        "where resultado_2.result in (2)";
        try {
            rs = exe.Select(query);
            DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }

            for(int i = 0; rs.next();i++){

                model.addRow(new Object[]{
                    rs.getString("orden"),
                    rs.getString("sku"),
                    rs.getString("cantidad"),
                    rs.getString("separado"),
                    rs.getString("despachado"),
                    rs.getString("cant_ingre"),
                    rs.getString("diferencia")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(jdSeparablesIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CargaIPendiente() {
        ExeSql exe = new ExeSql();
        ResultSet rs = null;
        String query = "select distinct on (result.orden) result.sku, result.cantidad, result.separado, result.despachado, result.resta, result.orden, result.ubicacion, \n" +
                        "(select mpp.cant from mt_productos mpp \n" +
                        " left join producto pp on pp.sku = mpp.sku \n" +
                        " where mpp.sku = result.sku and  ubicacion = 'TRAN.1001.1' and mpp.cant <>0 order by case when mpp.fecha_mod is null then EXTRACT(day from current_date-mpp.fecha) else EXTRACT(day from current_date-mpp.fecha_mod) END DESC) as ingreso\n" +
                        "\n" +
                        "from \n" +
                        "(select \n" +
                        "o.sku,\n" +
                        "o.rut,\n" +
                        "o.cantidad, o.separado, o.despachado,\n" +
                        "case when o.separado > 0\n" +
                        "then (o.cantidad - (o.separado) )\n" +
                        "else o.separado\n" +
                        "end as resta,\n" +
                        "CAST(o.codigo_oc as varchar) || '-' || o.orden as orden,\n" +
                        "mt.ubicacion\n" +
                        "from occhdet o\n" +
                        "left join mt_productos2 mt on  mt.sku = o.sku\n" +
                        ") result\n" +
                        "where result.resta > 0\n" +
                        "and result.sku in \n" +
                        "(select  p.sku  from mt_productos mp \n" +
                        "left join producto p on p.sku = mp.sku \n" +
                        "where ubicacion = 'TRAN.1001.1' and mp.cant <>0 \n" +
                        "order by case when mp.fecha_mod is null then EXTRACT(day from current_date-mp.fecha) else EXTRACT(day from current_date-mp.fecha_mod) END DESC)";
        try {
            rs = exe.Select(query);
            DefaultTableModel model = (DefaultTableModel) Grilla.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }

            for(int i = 0; rs.next();i++){

                model.addRow(new Object[]{
                    rs.getString("orden"),
                    rs.getString("sku"),
                    rs.getString("cantidad"),
                    rs.getString("separado"),
                    rs.getString("despachado"),
                    rs.getString("ingreso"),
                    rs.getString("resta")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(jdSeparablesIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CargarDatos() {
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                    Grilla.clearSelection();
                    lbcargando.setEnabled(true);
                    lbcargando.setVisible(true);
                    jButton1.setEnabled(false);
                    if(radio_ingreso.isSelected()){
                        CargaIngreso();
                    }
                    if(radio_pendientes.isSelected()){
                        CargaIPendiente();
                    }

                    lbcargando.setVisible(false);
                    lbcargando.setEnabled(false);
                    //Grilla.changeSelection(0, 0 , false, false);
                    jButton1.setEnabled(true);

                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        
            
        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
    }
    
    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed

    }//GEN-LAST:event_txSkuKeyPressed

    private void txSkuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyReleased
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
        Grilla.setRowSorter(sorter);
        String sku = txSku.getText().trim();
        if (sku.length()==0)
        {
            sorter.setRowFilter(null);
        }
        else{
            int cant=0;
            int ev=0;
            String precio = "";
            sorter.setRowFilter(RowFilter.regexFilter(sku));
        }
;
    }//GEN-LAST:event_txSkuKeyReleased

    private void txSkuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyTyped

    }//GEN-LAST:event_txSkuKeyTyped

    private void jDescripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescripcion2ActionPerformed
        if(!Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim().isEmpty()){
            StringSelection Voucher = new StringSelection(Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().trim());
            Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
            cb.setContents(Voucher, null);
        }
    }//GEN-LAST:event_jDescripcion2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CargarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txSkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSkuActionPerformed

    private void radio_pendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pendientesActionPerformed
        jButton1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_radio_pendientesActionPerformed

    private void radio_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_ingresoActionPerformed
        jButton1.doClick();  
    }//GEN-LAST:event_radio_ingresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdSeparablesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdSeparablesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdSeparablesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdSeparablesIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdSeparablesIngreso dialog = new jdSeparablesIngreso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jDescripcion2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu_Copiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcargando;
    private javax.swing.JRadioButton radio_ingreso;
    private javax.swing.JRadioButton radio_pendientes;
    private javax.swing.JTextField txSku;
    // End of variables declaration//GEN-END:variables
}
