/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdOC_PendientesFac;
import static Dialogos.jdOC_PendientesFac.pano;
import static Dialogos.jdOC_PendientesFac.pmes;
import static Dialogos.jdOC_PendientesFac.pmes_oc;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarPrv;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import Utilidades.ComboCodigos;
import static Utilidades.DocElect.carpeta;
import Utilidades.Ftp;
import java.awt.Desktop;
import java.awt.Window;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author David Alcaman
 */
public class pfBuscaDoc extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    public static ArrayList <String> Lista  = new ArrayList();
    
    /**
     * Creates new form pfReportePagosPrv
     */
    int id_doc;
    public pfBuscaDoc() {
        initComponents();
         boolean carga_imagen_dialog = false;
        lbCarga.setVisible(false);
        CargaDoc();
        btCancelar.setEnabled(true);
        
        
        
//         Calendar fecha = new GregorianCalendar();
//        //Obtenemos el valor del año, mes, día,
//        //hora, minuto y segundo del sistema
//        //usando el método get y el parámetro correspondiente
//        int año = fecha.get(Calendar.YEAR);
//        int mes = fecha.get(Calendar.MONTH);
//       /* int dia = fecha.get(Calendar.DAY_OF_MONTH);
//        int hora = fecha.get(Calendar.HOUR_OF_DAY);
//        int minuto = fecha.get(Calendar.MINUTE);
//        int segundo = fecha.get(Calendar.SECOND);*/
//        
//        String anox ="x";
//        String mesx ="x";
//        
//        anox = String.valueOf(año);
//        mesx = String.valueOf(mes+1);


      //  btExcel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        CboUsuario4 = new javax.swing.JComboBox<String>();
        lblVendedor12 = new javax.swing.JLabel();
        lblVendedor13 = new javax.swing.JLabel();
        CboTabla4 = new javax.swing.JComboBox<String>();
        lblVendedor14 = new javax.swing.JLabel();
        CboCambio4 = new javax.swing.JComboBox<String>();
        jPanel14 = new javax.swing.JPanel();
        dtDesde4 = new org.jdesktop.swingx.JXDatePicker();
        dtHasta4 = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        rbDesde4 = new javax.swing.JRadioButton();
        rbPeriodoTodos4 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Grilla4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblReg4 = new javax.swing.JLabel();
        btBuscar4 = new javax.swing.JButton();
        btExcel4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CboDoc = new javax.swing.JComboBox<String>();
        lblVendedor = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        lblVendedor3 = new javax.swing.JLabel();
        TxNumero = new java.awt.TextField();
        btCancelar = new javax.swing.JButton();
        lbCarga = new javax.swing.JLabel();

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PROVEEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CboUsuario4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboUsuario4ActionPerformed(evt);
            }
        });

        lblVendedor12.setText("USUARIO");

        lblVendedor13.setText("TABLA");

        CboTabla4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboTabla4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTabla4ActionPerformed(evt);
            }
        });

        lblVendedor14.setText("TIPO DE CAMBIO");

        CboCambio4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboCambio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboCambio4ActionPerformed(evt);
            }
        });

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PERIODO VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        dtDesde4.setEnabled(false);

        dtHasta4.setEnabled(false);
        dtHasta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtHasta4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Hasta");

        buttonGroup1.add(rbDesde4);
        rbDesde4.setText("Desde");
        rbDesde4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesde4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPeriodoTodos4);
        rbPeriodoTodos4.setText("Todos");
        rbPeriodoTodos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPeriodoTodos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(rbDesde4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDesde4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtHasta4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbPeriodoTodos4))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtHasta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtDesde4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(rbDesde4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPeriodoTodos4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Grilla4.setAutoCreateRowSorter(true);
        Grilla4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Fecha", "Tipo Cambio", "Tabla", "CAMPO1", "CAMPO2", "CAMPO3", "CAMPO4", "CAMPO5", "CAMPO6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grilla4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Grilla4);
        if (Grilla4.getColumnModel().getColumnCount() > 0) {
            Grilla4.getColumnModel().getColumn(0).setPreferredWidth(150);
            Grilla4.getColumnModel().getColumn(4).setResizable(false);
            Grilla4.getColumnModel().getColumn(5).setResizable(false);
            Grilla4.getColumnModel().getColumn(5).setPreferredWidth(75);
            Grilla4.getColumnModel().getColumn(6).setResizable(false);
            Grilla4.getColumnModel().getColumn(7).setResizable(false);
            Grilla4.getColumnModel().getColumn(7).setPreferredWidth(63);
            Grilla4.getColumnModel().getColumn(8).setResizable(false);
            Grilla4.getColumnModel().getColumn(8).setPreferredWidth(40);
            Grilla4.getColumnModel().getColumn(9).setResizable(false);
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Registros");

        lblReg4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReg4.setText("0");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(33, 33, 33)
                        .addComponent(lblReg4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblReg4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btBuscar4.setText("Buscar");
        btBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar4ActionPerformed(evt);
            }
        });

        btExcel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Order22.png"))); // NOI18N
        btExcel4.setText("Excel");
        btExcel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcel4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVendedor12)
                            .addComponent(CboUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVendedor13)
                            .addComponent(CboTabla4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVendedor14)
                            .addComponent(CboCambio4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExcel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor13)
                            .addComponent(lblVendedor12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CboTabla4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboCambio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(lblVendedor14)
                        .addGap(11, 11, 11)
                        .addComponent(btBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR DOCUMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        CboDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        CboDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboDocActionPerformed(evt);
            }
        });

        lblVendedor.setText("Tipo Documento");

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        lblVendedor3.setText("Número");

        TxNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxNumeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxNumeroKeyTyped(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCancelar.setBorderPainted(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        lbCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Carga.gif"))); // NOI18N
        lbCarga.setText("Cargando...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblVendedor)
                        .addGap(18, 18, 18)
                        .addComponent(CboDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblVendedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendedor)
                    .addComponent(CboDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVendedor3)
                    .addComponent(TxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCarga)
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 953, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 755, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("");
        jPanel3.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void CargaDoc(){
        DefaultComboBoxModel value;
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        CboDoc.removeAllItems();
        
//        CboProveedor.addItem("<Todos>");  
//        CboProveedor.setSelectedIndex(0);
        value =new DefaultComboBoxModel();
       
        
        
        try {
            Query="select tipo, nrodoc, nombre from tipo_doc\n" +
                    " order by tipo;";
            Rs = Sql.Select(Query);
            if(Sql.GetRowCount()==0) return;
           value.addElement(new ComboCodigos("Seleccione",0));     
           while(Rs.next()){
            value.addElement(new ComboCodigos(Rs.getString("nombre").trim(),Rs.getInt("nrodoc")));
            System.out.println(Rs.getString("tipo").trim());
           } 
           CboDoc.setModel(value);
           CboDoc.setSelectedIndex(0);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
   
public static String    BuscaArchivos(File ruta, String docElec){
        String nombre="";
          File archivos[]= ruta.listFiles();
          if (archivos != null){
            for(int i =0; i<archivos.length; i++){
              if (archivos[i].isDirectory()){
                  BuscaArchivos(archivos[i], docElec);
              }
              else
              {
                  Lista.add(archivos[i].getName());
                  if(archivos[i].getName().equals(docElec)){
                      nombre = archivos[i].getName();
                      System.out.println("Archivo Encontrado " + nombre );
                      break;
                  }
              }    
          } //end for
      } // end if
       return nombre;
        
    }// Fin Busca Archivos    
   
    
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        
        
         Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                
                lbCarga.setVisible(true);
                busca();
                lbCarga.setVisible(false);
                        
                } catch (Exception e) {
                    e.printStackTrace();
                    lbCarga.setVisible(false);
                }
            }
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        lbCarga.setVisible(false);
        
        
        
        
            
        
    }//GEN-LAST:event_btBuscarActionPerformed

 
    
//    public void busca(){
//    
//    ExeSql Sql = new ExeSql();
//        ResultSet Rs;
//        String Query="";
//        String path;
//        String server,user,pass,ruta_local="";
//        int puerto =21;
//        String rutaimage="";
//        String filtro="";
//        String archivo_local = "";
//     
//try {
//
//           final String Tipo;
//           final String Numero;
//           int cont =0; 
//            
//              if (CboDoc.getSelectedIndex() ==0){
//               fmMain.Mensaje("Debe Seleccionar un Tipo de Documento!!");
//               CboDoc.requestFocus();
//               return;
//                    }        
//           if (TxNumero.getText().trim().equals("")){
//               fmMain.Mensaje("Debe ingresar un Número de Documento!!");
//               TxNumero.requestFocus();
//               return;
//           }
//            Tipo=String.valueOf(id_doc);
//            System.out.println(Tipo);
//            Numero= TxNumero.getText().trim();
//            
////---------                     Trae Datos Ftp            ----------------------
////Creado por CRM - 15-06-2017            
// //trae datos ftp
//            server="";
//            puerto=0;
//            user=""; 
//            pass="";
//            	Rs = Sql.Select("SELECT * from conexiones where tipo='ftp_dte'");
//                if (Rs.next())
//                {
//                    if(!fmMain.GetInternet()){
//                        server = Rs.getString("serv");
//                        user  = Rs.getString("usu");
//                        puerto  = Rs.getInt("port");
//                        pass = Rs.getString("pass");
//                    }
//                    else {
//                        server = "179.57.172.101";
//                        user  = Rs.getString("usu");
//                        puerto  = 21;
//                        pass = Rs.getString("pass");
//                    }
//                }
//              
////                  //Verifica SO
//                    String sistema = System.getProperty("os.name").toLowerCase();
//                    File folder = new File("");
//                    if (sistema.contains("win"))
//                    {
//                         ruta_local = "c:/" + carpeta + "/";
//                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
//                    }
//                    else{
//                          ruta_local = "/" + carpeta + "/";
//                          folder = new File(ruta_local);
//                    }
//                    if (!folder.exists())
//                    {
//                        folder.mkdir();
//                    }
//                    
//                     System.out.println("Carpeta Asignada " + ruta_local );
//            
//                    // Primer buscara el archivo en ruta local
//                    filtro = "DTE"+Tipo+"-F" + Numero + "-nc.PDF";
//                    System.out.println("Busca en carpeta  local" + ruta_local +"/"+filtro );
//                    archivo_local = BuscaArchivos(new File(ruta_local),filtro);
//                    System.out.println("Busca archivo en FTP -->" + ruta_local +"/"+filtro );
//                    Ftp.busca_archivo_ftp(server, puerto, user, pass, ruta_local,archivo_local, filtro);
//                    System.out.println("Sale de Busca Archivo" + filtro );
//                        }
//catch (Exception e) {
//            System.out.println(e.getMessage());
//            fmMain.Mensaje("Existe una inconsistencia en la información.");
//        }finally{
//            Sql.Close();
//        }
//}
            
    
    
    public void busca(){
    
    ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        String path;
        String server,user,pass,ruta_local="";
        int puerto =21;
        String rutaimage="";
        String filtro="";
        String archivo_local = "";
     
try {

           final String Tipo;
           final String Numero;
           int cont =0; 
            
              if (CboDoc.getSelectedIndex() ==0){
               fmMain.Mensaje("Debe Seleccionar un Tipo de Documento!!");
               CboDoc.requestFocus();
               return;
                    }        
           if (TxNumero.getText().trim().equals("")){
               fmMain.Mensaje("Debe ingresar un Número de Documento!!");
               TxNumero.requestFocus();
               return;
           }
            Tipo=String.valueOf(id_doc);
            Numero= TxNumero.getText().trim();
            
//---------                     Trae Datos Ftp            ----------------------
//Creado por CRM - 15-06-2017            
 //trae datos ftp
            server="";
            puerto=0;
            user=""; 
            pass="";
            	Rs = Sql.Select("SELECT * from conexiones where tipo='ftp_dte'");
                if (Rs.next())
                {
                    if(!fmMain.GetInternet()){
                        server = Rs.getString("serv");
                        user  = Rs.getString("usu");
                        puerto  = Rs.getInt("port");
                        pass = Rs.getString("pass");
                    }
                    else {
                        server = "179.57.172.101";
                        user  = Rs.getString("usu");
                        puerto  = 21;
                        pass = Rs.getString("pass");
                    }
                }
              
//                  //Verifica SO
                    String sistema = System.getProperty("os.name").toLowerCase();
                    File folder = new File("");
                    if (sistema.contains("win"))
                    {
                         ruta_local = "c:/" + carpeta + "/";
                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
                    }
                    else{
                          ruta_local = "/" + carpeta + "/";
                          folder = new File(ruta_local);
                    }
                    if (!folder.exists())
                    {
                        folder.mkdir();
                    }
                    
                     System.out.println("Carpeta Asignada " + ruta_local );
            
                    // Primer buscara el archivo en ruta local
                    filtro = Tipo + "F" + Numero + ".pdf";
                    System.out.println("Busca en carpeta  local" + ruta_local +"/"+filtro );
                    archivo_local = BuscaArchivos(new File(ruta_local),filtro);
                    System.out.println("Busca archivo en FTP -->" + ruta_local +"/"+filtro );
                    Ftp.busca_archivo_ftp(server, puerto, user, pass, ruta_local,archivo_local, filtro);
                    System.out.println("Sale de Busca Archivo" + filtro );
                        }
catch (Exception e) {
            fmMain.Mensaje("Existe una inconsistencia en la información.");
        }finally{
            Sql.Close();
        }
}
    
    
    
    
    private void CboDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboDocActionPerformed
try{    
        ComboCodigos usuario = (ComboCodigos) CboDoc.getSelectedItem() ;
         
        if (CboDoc.getSelectedItem()!= null){
            id_doc = usuario.getId();
            System.out.println("id del documenro: " +  id_doc);
        }
        
          
    } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }       

    }//GEN-LAST:event_CboDocActionPerformed

    private void CboUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboUsuario4ActionPerformed

    private void CboTabla4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTabla4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboTabla4ActionPerformed

    private void CboCambio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboCambio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboCambio4ActionPerformed

    private void dtHasta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtHasta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtHasta4ActionPerformed

    private void rbDesde4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesde4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDesde4ActionPerformed

    private void rbPeriodoTodos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPeriodoTodos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPeriodoTodos4ActionPerformed

    private void Grilla4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grilla4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Grilla4MouseClicked

    private void btBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscar4ActionPerformed

    private void btExcel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcel4ActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        CboDoc.setSelectedIndex(0);
        CboDoc.requestFocus();
        TxNumero.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void TxNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNumeroKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(Character.isLetter(c)) { 
                 getToolkit().beep(); 
                 evt.consume(); 
                 System.out.println("Ingreso una Letra -->" + c ); }
     
     
     
    }//GEN-LAST:event_TxNumeroKeyTyped

    private void TxNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNumeroKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btBuscar.doClick();     
         } 
    }//GEN-LAST:event_TxNumeroKeyPressed





//6700

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboCambio4;
    private javax.swing.JComboBox<String> CboDoc;
    private javax.swing.JComboBox<String> CboTabla4;
    private javax.swing.JComboBox<String> CboUsuario4;
    private javax.swing.JTable Grilla4;
    private java.awt.TextField TxNumero;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar4;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcel4;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker dtDesde4;
    private org.jdesktop.swingx.JXDatePicker dtHasta4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbCarga;
    private javax.swing.JLabel lblReg4;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JLabel lblVendedor12;
    private javax.swing.JLabel lblVendedor13;
    private javax.swing.JLabel lblVendedor14;
    private javax.swing.JLabel lblVendedor3;
    private javax.swing.JRadioButton rbDesde4;
    private javax.swing.JRadioButton rbPeriodoTodos4;
    // End of variables declaration//GEN-END:variables


}
