/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarCliPrv;
import Dialogos.jdCliBlogAgregar;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarCli;
import Formularios.fmMain;
import static PanelForm.pfBuscaDoc.BuscaArchivos;
import static Utilidades.DocElect.carpeta;
import Utilidades.Ftp;
import static Utilidades.Ftp.busca;
import Utilidades.ImageSelection;
import Utilidades.ImgTabla;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.math.BigInteger;
import java.net.URL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author David Alcaman
 */

public class pfCLI_EstadoCXC extends javax.swing.JPanel {
DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
boolean CargaExterior;
String FacsExterior;
int IdCartolaBancaria;

    /**
     * Creates new form pfCLI_EstadoCXC
     */
    public pfCLI_EstadoCXC() {
        initComponents();
        IdCartolaBancaria=0;
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(9).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(10).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(11).setCellRenderer(rightRenderer);
        
        txRutBlog.setVisible(true);
        txCodigo_Oc.setVisible(false);
        txRutBlog.setVisible(false);
        CargaExterior = false;
        
        Grilla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(Grilla.getSelectedRowCount()>0){
                    CargaDatosContacto(Grilla.getValueAt(Grilla.getSelectedRow(),1).toString(),Grilla.getValueAt(Grilla.getSelectedRow(),3).toString());
                    SumaMontosSeleccionados();
                    SumaPagadosSeleccionados();
                    SumaDeudasSeleccionados();
                }
      
            }

        });
        Grilla.setDefaultRenderer(Object.class, new Utilidades.TableCellRendererColor());
    }
    

    public void SetRut(String rut,String occ) {
        
        String[] parts = occ.split("-");
        System.out.println("RUT: '"+rut+"', OCC: '"+occ+"'");
        System.out.println("RUT: '"+rut+"', OCC: '"+parts[0]+"'");
        txRut.setEnabled(true);
        rbRut.setSelected(true);
        btIr.setEnabled(true);
        txCliente.setEnabled(true);
        cbCodigo_Oc.setEnabled(true);
        txRut.setText(rut);
        CargaCliente(rut);
        cbCodigo_Oc.setSelectedItem(parts[0]);
        
        
        CargaTabla();
        CargaTabla();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuAbrirPDF = new javax.swing.JMenuItem();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbVencidas = new javax.swing.JRadioButton();
        rbVigentes = new javax.swing.JRadioButton();
        rbPagadas = new javax.swing.JRadioButton();
        rbTodas = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rbRut = new javax.swing.JRadioButton();
        rbRutTodos = new javax.swing.JRadioButton();
        txRut = new javax.swing.JTextField();
        txCliente = new javax.swing.JTextField();
        btIr = new javax.swing.JButton();
        cbCodigo_Oc = new javax.swing.JComboBox();
        chkAutorizacion = new javax.swing.JCheckBox();
        btBuscar = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        rbFacturas = new javax.swing.JRadioButton();
        rbBoletas = new javax.swing.JRadioButton();
        rbDocTodas = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lbSumMontos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbContPagos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbSumSeleccionMonto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbSumPagado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbSumDeuda = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbSumSeleccionPagado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbSumSeleccionDeuda = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txContacto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txFono = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txCodigo_Oc = new javax.swing.JTextField();
        txRutBlog = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaBlog = new javax.swing.JTable();
        btAgregarBlog = new javax.swing.JButton();
        btEliminaBlog = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        rbMonto = new javax.swing.JRadioButton();
        rbMontoTodos = new javax.swing.JRadioButton();
        txMonto = new javax.swing.JTextField();
        btEmail = new javax.swing.JButton();
        chkContactos = new javax.swing.JCheckBox();
        chkBloqueos = new javax.swing.JCheckBox();
        chkPagos = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txSku = new javax.swing.JTextField();
        lbcargando = new javax.swing.JLabel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/copy.png"))); // NOI18N
        jMenuItem1.setText("Copiar Estado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar Totales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        MnuAbrirPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/pdf.png"))); // NOI18N
        MnuAbrirPDF.setText("Abrir en PDF");
        MnuAbrirPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAbrirPDFActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnuAbrirPDF);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonGroup1.add(rbVencidas);
        rbVencidas.setSelected(true);
        rbVencidas.setText("Vencidas");

        buttonGroup1.add(rbVigentes);
        rbVigentes.setText("Vigentes");

        buttonGroup1.add(rbPagadas);
        rbPagadas.setText("Pagadas");

        buttonGroup1.add(rbTodas);
        rbTodas.setText("Todas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbVigentes)
                    .addComponent(rbVencidas)
                    .addComponent(rbPagadas)
                    .addComponent(rbTodas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVigentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPagadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTodas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonGroup2.add(rbRut);
        rbRut.setText("Rut");
        rbRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRutActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbRutTodos);
        rbRutTodos.setSelected(true);
        rbRutTodos.setText("Todos");
        rbRutTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRutTodosActionPerformed(evt);
            }
        });

        txRut.setEnabled(false);
        txRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txRutKeyPressed(evt);
            }
        });

        txCliente.setEditable(false);
        txCliente.setEnabled(false);

        btIr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btIr.setBorderPainted(false);
        btIr.setEnabled(false);
        btIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIrActionPerformed(evt);
            }
        });

        cbCodigo_Oc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCodigo_Oc.setEnabled(false);
        cbCodigo_Oc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCodigo_OcActionPerformed(evt);
            }
        });

        chkAutorizacion.setText("Con AUTORIZACION");
        chkAutorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAutorizacionActionPerformed(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/search16.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Peso16.png"))); // NOI18N
        btPagar.setText("Pagar");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });

        buttonGroup4.add(rbFacturas);
        rbFacturas.setText("Facturas");
        rbFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFacturasActionPerformed(evt);
            }
        });

        buttonGroup4.add(rbBoletas);
        rbBoletas.setText("Boletas");

        buttonGroup4.add(rbDocTodas);
        rbDocTodas.setSelected(true);
        rbDocTodas.setText("Todas");
        rbDocTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDocTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chkAutorizacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbRut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbRutTodos))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCodigo_Oc, 0, 206, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFacturas)
                                    .addComponent(rbBoletas)
                                    .addComponent(rbDocTodas))
                                .addGap(169, 169, 169)
                                .addComponent(btBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbRut)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btIr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCodigo_Oc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbRutTodos)
                            .addComponent(btBuscar)
                            .addComponent(btPagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkAutorizacion)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbFacturas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbBoletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDocTodas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbSumMontos.setText("0.00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nro Pagos:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Monto Total");

        lbContPagos.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total Selección Monto");

        lbSumSeleccionMonto.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Pagado Total");

        lbSumPagado.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Deuda Total");

        lbSumDeuda.setText("0.00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total Selección Pagado");

        lbSumSeleccionPagado.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Total Selección Deuda");

        lbSumSeleccionDeuda.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbContPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSumMontos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSumPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSumDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSumSeleccionMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lbSumSeleccionPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(lbSumSeleccionDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lbContPagos)
                    .addComponent(lbSumMontos)
                    .addComponent(jLabel5)
                    .addComponent(lbSumSeleccionMonto)
                    .addComponent(jLabel8)
                    .addComponent(lbSumPagado)
                    .addComponent(jLabel9)
                    .addComponent(lbSumDeuda)
                    .addComponent(jLabel10)
                    .addComponent(lbSumSeleccionPagado)
                    .addComponent(jLabel11)
                    .addComponent(lbSumSeleccionDeuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contacto"));

        jLabel2.setText("Contacto");

        jLabel6.setText("Fono");

        jLabel7.setText("Correo");

        txCodigo_Oc.setText("jTextField1");

        txRutBlog.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txContacto)
                    .addComponent(txEmail)
                    .addComponent(txFono, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCodigo_Oc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txRutBlog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCodigo_Oc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txRutBlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        GrillaBlog.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        GrillaBlog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Historial", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaBlog.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(GrillaBlog);
        if (GrillaBlog.getColumnModel().getColumnCount() > 0) {
            GrillaBlog.getColumnModel().getColumn(0).setMinWidth(30);
            GrillaBlog.getColumnModel().getColumn(0).setPreferredWidth(30);
            GrillaBlog.getColumnModel().getColumn(0).setMaxWidth(30);
            GrillaBlog.getColumnModel().getColumn(2).setMinWidth(0);
            GrillaBlog.getColumnModel().getColumn(2).setPreferredWidth(0);
            GrillaBlog.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        btAgregarBlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btAgregarBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarBlogActionPerformed(evt);
            }
        });

        btEliminaBlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btEliminaBlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaBlogActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Monto"));

        buttonGroup3.add(rbMonto);
        rbMonto.setText("Monto");
        rbMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMontoActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbMontoTodos);
        rbMontoTodos.setSelected(true);
        rbMontoTodos.setText("Todos");
        rbMontoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMontoTodosActionPerformed(evt);
            }
        });

        txMonto.setEnabled(false);
        txMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txMontoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(rbMontoTodos)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMonto)
                    .addComponent(txMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMontoTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btEmail.setText("email");
        btEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmailActionPerformed(evt);
            }
        });

        chkContactos.setSelected(true);
        chkContactos.setText("Contactos");
        chkContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkContactosActionPerformed(evt);
            }
        });

        chkBloqueos.setText("Bloqueos");
        chkBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBloqueosActionPerformed(evt);
            }
        });

        chkPagos.setText("Pagos");
        chkPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPagosActionPerformed(evt);
            }
        });

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Rut", "Cliente", "Codigo", "Orden", "Documento", "Fecha", "Vencimiento", "Dias", "Monto", "Pagado", "Deuda", "id_cuota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.setComponentPopupMenu(jPopupMenu1);
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(65);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(1).setMinWidth(60);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(60);
            Grilla.getColumnModel().getColumn(2).setMinWidth(250);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(250);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(250);
            Grilla.getColumnModel().getColumn(3).setMinWidth(65);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(4).setMinWidth(65);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(5).setMinWidth(65);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(6).setMinWidth(70);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(7).setMinWidth(70);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(8).setMinWidth(40);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(40);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(40);
            Grilla.getColumnModel().getColumn(9).setMinWidth(65);
            Grilla.getColumnModel().getColumn(9).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(9).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(10).setMinWidth(65);
            Grilla.getColumnModel().getColumn(10).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(10).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(11).setMinWidth(65);
            Grilla.getColumnModel().getColumn(11).setPreferredWidth(65);
            Grilla.getColumnModel().getColumn(11).setMaxWidth(65);
            Grilla.getColumnModel().getColumn(12).setMinWidth(0);
            Grilla.getColumnModel().getColumn(12).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("FILTRO:");

        txSku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSkuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txSkuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txSkuKeyTyped(evt);
            }
        });

        lbcargando.setText("Cargando");
        lbcargando.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSku))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbcargando)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbcargando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txSku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkContactos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkBloqueos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPagos))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAgregarBlog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEliminaBlog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEmail))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAgregarBlog)
                            .addComponent(btEliminaBlog)
                            .addComponent(btEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkContactos)
                            .addComponent(chkBloqueos)
                            .addComponent(chkPagos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void CargaClienteCartera(String Rut){
        CargaExterior = false;
        rbVencidas.setSelected(true);
        rbRut.doClick();
        txRut.setText(Rut);
        btIr.doClick();
        btBuscar.doClick();
    }
    public void CargaFacturas(String Rut,String Codigo_Oc,String Facturas,int LaId){
        CargaExterior=true;
        FacsExterior = Facturas;
        rbTodas.setSelected(true);
        rbRut.doClick();
        txRut.setText(Rut);
        btIr.doClick();
        cbCodigo_Oc.setSelectedItem(Codigo_Oc.trim());
        Grilla.selectAll();
        rbPagadas.setEnabled(false);
        rbVencidas.setEnabled(false);
        rbVigentes.setEnabled(false);
        rbRutTodos.setEnabled(false);
        cbCodigo_Oc.setEnabled(false);
        rbMonto.setEnabled(false);
        btBuscar.setEnabled(false);
        IdCartolaBancaria = LaId;
        
//        String Fac[] = Facturas.split("-");
        
    }
    
    private void txRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txRutKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        btIr.doClick();
    }//GEN-LAST:event_txRutKeyPressed

    private void rbRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRutActionPerformed
        if(rbRut.isSelected()){
            txRut.setEnabled(true);
            txCliente.setEnabled(true);
            cbCodigo_Oc.setEnabled(true);
            btIr.setEnabled(true);
            txRut.requestFocus();
            chkAutorizacion.setEnabled(false);
            chkAutorizacion.setSelected(false);
        }
            
    }//GEN-LAST:event_rbRutActionPerformed

    private void btIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIrActionPerformed
        if (!txRut.getText().isEmpty()) {
            CargaCliente(txRut.getText());
        } else {
            jdBuscarCliPrv BPC = new jdBuscarCliPrv(null, true);
            BPC.setLocationRelativeTo(null);
            BPC.setTitle("Buscar Cliente");
            BPC.SetTipo(1);
            BPC.setVisible(true);
            CargaCliente(BPC.GetRut());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btIrActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        Runnable miRunnable = new Runnable() {
            public void run() {
                try{
                    Grilla.clearSelection();
                    lbcargando.setEnabled(true);
                    lbcargando.setVisible(true);


                    CargaTabla();

                    lbcargando.setVisible(false);
                    lbcargando.setEnabled(false);
                    //Grilla.changeSelection(0, 0 , false, false);


                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        Thread hilo = new Thread(miRunnable);
        hilo.start();
        
            
        lbcargando.setText("Cargando.....");
        URL urlInfo =  this.getClass().getResource("/Iconos16/wait.gif");
        ImageIcon IconoInfo =  new ImageIcon(urlInfo); 
        lbcargando.setIcon(IconoInfo);
        lbcargando.setForeground(Color.red);
    }//GEN-LAST:event_btBuscarActionPerformed
    
    
    public void CargaTabla() {
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        int ContPagos=0;
        BigInteger SumMontos = new BigInteger("0");    
        BigInteger SumPagados = new BigInteger("0");   
        BigInteger SumDeudas = new BigInteger("0");   
        
        while(TableModel.getRowCount()>0)
                        TableModel.removeRow(0);        
        
        try {
            Query = "select distinct case cxc.estado when 0 then 'Pendiente' when 1 then 'Vencida' when 2 then 'Parcial' else 'Pagado' end as Estado,\n" +
                    "cxc.rut,case when c.nombre is null then 'No Definido' else c.nombre end as nombre, \n" +
                    "cxc.codigo_oc,case when cli.occh is null then '--' else cli.occh end as occh,\n" +
                    "cxc.nrodocto,cxc.femision,cxc.femision + cast((select valor from par_general where tipo='PLAZOSCOBRANZA' and codigo=0) as integer) as fpago ,cxc.monto\n" +
                    ",cxc.pagado,cxc.monto-cxc.pagado as saldo,cxc.id, case cxc.estado when 3 then (clipa.fechapago-cxc.femision) ELSE (CURRENT_DATE-cxc.femision) end  as Dias\n" +
                    "from cli_cuentasxcobrar cxc\n" +
                    "left join cliente c on c.rut=cxc.rut\n" +
                    "left join ctactecli cli on cli.tipdocto=cxc.tipdocto and cli.rut=cxc.rut and cli.nrodocto=cxc.nrodocto\n" +
                    "left join cli_pagos clipa on clipa.cuenta =cxc.id \n ";
            
            /*
            Estado
            */
            if(rbVencidas.isSelected())
                Query = Query + "where cxc.estado in (0,1,2) and current_date - cxc.femision > (select valor from par_general where tipo='PLAZOSCOBRANZA' and codigo=0) \n";
            else if(rbVigentes.isSelected())
                Query = Query + "where cxc.estado in (0,2) and current_date - cxc.femision <= (select valor from par_general where tipo='PLAZOSCOBRANZA' and codigo=0) \n";
            else if(rbPagadas.isSelected())
                Query = Query + "where cxc.estado = 3 and clipa.tipopago<>4 \n";
            else
                Query = Query + "where cxc.estado >= 0 \n";
            
            
             /*
            Documento
            */
            
            if(rbFacturas.isSelected()){
            
               
                Query = Query + "and cxc.tipdocto in ('FAC') \n";
            
            }else  if(rbBoletas.isSelected()) {
            
                Query = Query + "and cxc.tipdocto in ('BOC') \n";
            
            }
            
            /*
            Cliente
            */
            
            if(rbRut.isSelected())
                {
                String Codigo_Oc = cbCodigo_Oc.getSelectedItem().toString().trim();
                if (Codigo_Oc.equals("Todos"))
                    {
                    Query = Query + " and cxc.rut=" + txRut.getText().trim() +"\n";
                    }
                else{
                    Query = Query + " and cxc.rut=" + txRut.getText().trim() + " and cxc.codigo_oc="+ Codigo_Oc +"\n";
                    }
                }
            /*
            Monto
            */
            if(rbMonto.isSelected() && !txMonto.getText().isEmpty())
                Query = Query + "and cxc.monto=" + txMonto.getText() + "\n";
            
            if(CargaExterior)
                Query = Query + "and cxc.nrodocto in (" + FacsExterior + ") \n";
            
            Query = Query + " order by Dias desc";
            
            System.out.println(Query);
            Rs = Sql.Select(Query);
            
            while(Rs.next()){
                ContPagos++;
                SumMontos = SumMontos.add(new BigInteger(Rs.getString("monto"))) ;
                SumPagados = SumPagados.add(new BigInteger(Rs.getString("pagado"))) ;
                SumDeudas = SumDeudas.add(new BigInteger(Rs.getString("saldo"))) ;
                
                TableModel.addRow(new Object[]{Rs.getString("estado").trim(), 
                                               Rs.getString("rut").trim(), 
                                               Rs.getString("nombre").trim(),
                                               Rs.getString("codigo_oc").trim(),
                                               Rs.getString("occh").trim(),
                                              // Rs.getString("nrodocto").trim(), 
                                               Rs.getInt("nrodocto"),
                                               Rs.getString("femision").trim(), 
                                               Rs.getString("fpago").trim(), 
                                               Rs.getInt("Dias"), 
                                               fmMain.FormatoTotal(Rs.getDouble("monto")),
                                               fmMain.FormatoTotal(Rs.getDouble("pagado")),
                                               fmMain.FormatoTotal(Rs.getDouble("saldo")),
                                               Rs.getString("id").trim()});
            }
            lbSumMontos.setText(fmMain.FormatoNumeroBig(SumMontos));
            lbContPagos.setText(fmMain.FormatoTotal(ContPagos));
            lbSumPagado.setText(fmMain.FormatoNumeroBig(SumPagados));
            lbSumDeuda.setText(fmMain.FormatoNumeroBig(SumDeudas));
            
            if(!rbRut.isSelected()){
                Grilla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                System.out.println("single");
            }
            else{
                Grilla.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
                System.out.println("multiple");
            }
            
            if(chkAutorizacion.isSelected()){
                Grilla.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
                System.out.println("single");
            }
            Grilla.setRowSelectionAllowed(true);
            Grilla.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    
    private void CargaBlog(String Rut,String Codigo_Oc){
        ExeSql Sql= new ExeSql();
        ResultSet Rs;
        GrillaBlog.setDefaultRenderer(Object.class, new ImgTabla());
        DefaultTableModel tm = (DefaultTableModel) GrillaBlog.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy - hh:mm");
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MMM-yyyy");
        
        JLabel lbCall = new JLabel();
        JLabel lbMail = new JLabel();
        JLabel lbBloqueo = new JLabel();
        JLabel lbDesbloqueo = new JLabel();
        JLabel lbPago = new JLabel();
        
        URL urlCall = this.getClass().getResource("/Iconos/Llamada.png");  
        URL urlMail = this.getClass().getResource("/Iconos/email.png");  
        URL urlBloqueo = this.getClass().getResource("/Iconos/bloquear.png");  
        URL urlDesbloqueo = this.getClass().getResource("/Iconos/Desbloquear.png");  
        URL urlPago = this.getClass().getResource("/Iconos/pago.png");  
        
        ImageIcon IconoCall =  new ImageIcon(urlCall); 
        ImageIcon IconoMail =  new ImageIcon(urlMail); 
        ImageIcon IconoBloqueo =  new ImageIcon(urlBloqueo); 
        ImageIcon IconoDesbloqueo =  new ImageIcon(urlDesbloqueo); 
        ImageIcon IconoPago =  new ImageIcon(urlPago); 
        
        lbCall.setIcon(IconoCall);
        lbMail.setIcon(IconoMail);
        lbBloqueo.setIcon(IconoBloqueo);
        lbDesbloqueo.setIcon(IconoDesbloqueo);
        lbPago.setIcon(IconoPago);
        
        String Tipo = " and tipo in (";
        
        if(chkContactos.isSelected())
            Tipo = Tipo + "1,2,";
        if(chkBloqueos.isSelected())
            Tipo = Tipo + "3,4,";
        if(chkPagos.isSelected())
            Tipo = Tipo + "5,";
        
        Tipo = Tipo.substring(1, Tipo.length()-1);
        
        Tipo = Tipo + ") \n";
        
        while(tm.getRowCount()>0)
            tm.removeRow(0); 
        
        try {
            
        
                    Rs = Sql.Select("select tipo,fecha,usuario,texto,id,fcompromiso\n" +
                            "from cli_cobranzablog\n" +
                            "where rut="+ Rut +"\n" +
                            "and nrodocto='"+ Grilla.getValueAt(Grilla.getSelectedRow(),5) +"'\n" +
                            "and codigo_oc="+ Codigo_Oc +"\n" +
                            Tipo +
                            "order by id desc");
            while(Rs.next()){
                
                //Tipo 0 = Llamada
                if(Rs.getInt("tipo")==1){
                    tm.addRow(new Object[]{lbCall,sdf.format(Rs.getTimestamp("fecha")),Rs.getString("id")});
                    
                }
                //Tipo 1 = Correo
                else if(Rs.getInt("tipo")==2) {
                    tm.addRow(new Object[]{lbMail,sdf.format(Rs.getTimestamp("fecha")),Rs.getString("id")});
                }
                // Tipo 2 = Bloque
                else if(Rs.getInt("tipo")==3) {
                    tm.addRow(new Object[]{lbBloqueo,sdf.format(Rs.getTimestamp("fecha")),Rs.getString("id")});
                }
                // Tipo 3 = Desbloqueo
                else if(Rs.getInt("tipo")==4) {
                    tm.addRow(new Object[]{lbDesbloqueo,sdf.format(Rs.getTimestamp("fecha")),Rs.getString("id")});
                }
                // Tipo 5 = Pago
                else if(Rs.getInt("tipo")==5) {
                    tm.addRow(new Object[]{lbPago,sdf.format(Rs.getTimestamp("fecha")),Rs.getString("id")});
                }
                
                
                //Mensaje
                tm.addRow(new Object[]{" ",Rs.getString("texto"),Rs.getString("id")});
                
                try {
                    tm.addRow(new Object[]{" ", "Compromiso: " + sdf2.format(Rs.getTimestamp("fcompromiso"))});
                } catch (Exception e) {
                }
                
        
                
            }
            } catch (Exception e) {
                System.out.println(e.getMessage());
        } finally{
            Sql.Close();
        }
    }
    private void SumaMontosSeleccionados(){
        int[] filasSelec = Grilla.getSelectedRows();
        BigInteger SumMontos = new BigInteger("0");    
        String Celda;
       
        
            for( int i = 0; i < filasSelec.length; i++){
                Celda = Grilla.getValueAt(filasSelec[i], 9).toString();
                if(Grilla.getValueAt(filasSelec[i], 1).toString().isEmpty())
                    continue;
                Celda = fmMain.SetGuardar(Celda);
                
                SumMontos = SumMontos.add(new BigInteger(Celda)) ;
                //fmMain.SetGuardar(TOOL_TIP_TEXT_KEY)
            }
            lbSumSeleccionMonto.setText(fmMain.FormatoNumeroBig(SumMontos));
            
    }
    
    private void SumaPagadosSeleccionados(){
        int[] filasSelec = Grilla.getSelectedRows();
        BigInteger SumMontos = new BigInteger("0");    
        String Celda;
       
        
            for( int i = 0; i < filasSelec.length; i++){
                Celda = Grilla.getValueAt(filasSelec[i], 10).toString();
                if(Grilla.getValueAt(filasSelec[i], 1).toString().isEmpty())
                    continue;
                Celda = fmMain.SetGuardar(Celda);
                
                SumMontos = SumMontos.add(new BigInteger(Celda)) ;
                //fmMain.SetGuardar(TOOL_TIP_TEXT_KEY)
            }
            lbSumSeleccionPagado.setText(fmMain.FormatoNumeroBig(SumMontos));
            
    }
    private void SumaDeudasSeleccionados(){
        int[] filasSelec = Grilla.getSelectedRows();
        BigInteger SumMontos = new BigInteger("0");    
        String Celda;
       
        
            for( int i = 0; i < filasSelec.length; i++){
                Celda = Grilla.getValueAt(filasSelec[i], 11).toString();
                if(Grilla.getValueAt(filasSelec[i], 1).toString().isEmpty())
                    continue;
                Celda = fmMain.SetGuardar(Celda);
                
                SumMontos = SumMontos.add(new BigInteger(Celda)) ;
                //fmMain.SetGuardar(TOOL_TIP_TEXT_KEY)
            }
            lbSumSeleccionDeuda.setText(fmMain.FormatoNumeroBig(SumMontos));
            
    }
    private void CargaDatosContacto(String Rut,String Codigo_Oc){
        ExeSql Sql= new ExeSql();
        ResultSet Rs;
        
        try {
            Rs = Sql.Select("select cl.nombre, c.nombre as contacto,c.fono,c.email\n" +
                            "from clicontactopersonas c\n" +
                            "left join cliente cl on c.rut=cl.rut\n" +
                            "where c.rut="+ Rut +"\n" +
                            "and c.codigo_oc="+ Codigo_Oc +"\n" +
                            "limit 1");
            if(Sql.GetRowCount()>0){
                Rs.next();
                txContacto.setText(Rs.getString("contacto").trim());
                txFono.setText(Rs.getString("fono").trim());
                txEmail.setText(Rs.getString("email").trim());
                txCodigo_Oc.setText(Codigo_Oc);
                txRutBlog.setText(Rut);
            }
            
            /*
            
            */
            Rs = Sql.Select("select tipo,fecha,usuario,texto,id,fcompromiso\n" +
                            "from cli_cobranzablog\n" +
                            "where rut="+ Rut +"\n" +
                            "and codigo_oc="+ Codigo_Oc +"\n" +
                            "order by id desc");
            
            CargaBlog(Rut, Codigo_Oc);
                
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
            
        
    }
    
    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(),0).toString().equals("Pendiente")){
            jdPagadoPrvCli Pagado = new jdPagadoPrvCli(null, true);
            Pagado.setLocationRelativeTo(null);
            Pagado.setTitle("Pagos Cliente");
            Pagado.CargaPagosCli(Grilla.getValueAt(Grilla.getSelectedRow(), 12).toString().trim());  
            Pagado.setVisible(true);
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void btAgregarBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarBlogActionPerformed
            jdCliBlogAgregar AddBlog = new jdCliBlogAgregar(null, true);
            AddBlog.SetDatosClientes(txRutBlog.getText(), txCodigo_Oc.getText(), Grilla.getValueAt(Grilla.getSelectedRow(), 5).toString().trim());
            AddBlog.setTitle("Nuevo Evento");
            AddBlog.setLocationRelativeTo(btAgregarBlog);
            AddBlog.setVisible(true);
            if(AddBlog.GetGuardar())
                CargaDatosContacto(txRutBlog.getText(),txCodigo_Oc.getText());
    }//GEN-LAST:event_btAgregarBlogActionPerformed

    private void btEliminaBlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaBlogActionPerformed
        if(fmMain.OkCancel("¿Eliminar el registro")== JOptionPane.OK_OPTION){
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("delete from cli_cobranzablog where id=" +  GrillaBlog.getValueAt(GrillaBlog.getSelectedRow(),2));
                Sql.Commit();
                CargaDatosContacto(txRutBlog.getText(),txCodigo_Oc.getText());
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }finally{
                Sql.Close();
            }
        }
    }//GEN-LAST:event_btEliminaBlogActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed

        
        if(Grilla.getSelectedRowCount()>0){
            String Ids="";
            int[] filasSelec = Grilla.getSelectedRows();
            for( int i = 0; i < filasSelec.length; i++){
                if(Grilla.getValueAt(filasSelec[i],0).toString().equals("Pagado")){
                    fmMain.Mensaje("factura seleccionada, ya esta pagada");
                    return;
                }
                Ids = Ids + Grilla.getValueAt(filasSelec[i], 12).toString().trim() + ",";
            }
            Ids = Ids.substring(0, Ids.length()-1);
            jdPagarCli PagarCuotaCli = new jdPagarCli(null, true);
            PagarCuotaCli.setLocationRelativeTo(null);
            PagarCuotaCli.setTitle("Pagar Factura Cliente");
            PagarCuotaCli.CargaPago(Ids,filasSelec.length,IdCartolaBancaria);
            if (chkAutorizacion.isSelected())
            {
                PagarCuotaCli.btPagar.setVisible(false);
                PagarCuotaCli.btSolicitarAuto.setVisible(true);
                PagarCuotaCli.btAjuste.setVisible(true);
            }
            else{
              PagarCuotaCli.btPagar.setVisible(true);
              PagarCuotaCli.btSolicitarAuto.setVisible(false);
              PagarCuotaCli.btAjuste.setVisible(false);
            }
            
            PagarCuotaCli.setVisible(true);
            if (PagarCuotaCli.GetPagado() == 1) {
                //Grilla.setValueAt("Pagado", Grilla.getSelectedRow(), 0);
                for( int i = 0; i < filasSelec.length; i++){
                    Grilla.setValueAt("Pagado", filasSelec[i], 0);
                }
            }
        }
        
        
    }//GEN-LAST:event_btPagarActionPerformed

    private void rbMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMontoActionPerformed
        if(rbMonto.isSelected())txMonto.setEnabled(true);
    }//GEN-LAST:event_rbMontoActionPerformed

    private void rbMontoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMontoTodosActionPerformed
        if(rbMontoTodos.isSelected()) txMonto.setEnabled(false);
    }//GEN-LAST:event_rbMontoTodosActionPerformed

    private void txMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMontoKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txMontoKeyTyped

    private void rbRutTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRutTodosActionPerformed
        if(!rbRut.isSelected()){
            txRut.setEnabled(false);
            txCliente.setEnabled(false);
            cbCodigo_Oc.setEnabled(false);
            btIr.setEnabled(true);
            txRut.requestFocus();
            chkAutorizacion.setEnabled(true);
        }
    }//GEN-LAST:event_rbRutTodosActionPerformed

    private void btEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmailActionPerformed
        String Mensaje="Estimado Cliente\n saludos";
        
        
        try {
            Mensaje = java.net.URLEncoder.encode(Mensaje, "utf-8");
            Mensaje = Mensaje.replace("+", "%20");
            System.out.println(Mensaje);
            java.awt.Desktop.getDesktop().mail(java.net.URI.create("mailto:nadie@nadie.com?cc=juanperez@yahoo.com&cco=juanperez2@yahoo.com&subject=prueba&body="+ Mensaje));
            //Process p = Runtime.getRuntime().exec ("'mailto:nadie@nadie.com?cc=juanperez@yahoo.com&cco=juanperez2@yahoo.com&subject=prueba'"); 
//            Process p=Runtime.getRuntime().exec ("cmd /c dir");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btEmailActionPerformed

    private void cbCodigo_OcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCodigo_OcActionPerformed
        if(!txRut.getText().isEmpty())
            btBuscar.doClick();
    }//GEN-LAST:event_cbCodigo_OcActionPerformed

    private void chkContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkContactosActionPerformed
        CargaBlog(txRut.getText(), cbCodigo_Oc.getSelectedItem().toString().trim());
    }//GEN-LAST:event_chkContactosActionPerformed

    private void chkBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBloqueosActionPerformed
        CargaBlog(txRut.getText(), cbCodigo_Oc.getSelectedItem().toString().trim());
    }//GEN-LAST:event_chkBloqueosActionPerformed

    private void chkPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPagosActionPerformed
        CargaBlog(txRut.getText(), cbCodigo_Oc.getSelectedItem().toString().trim());
    }//GEN-LAST:event_chkPagosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Rectangle rect = Grilla.getBounds();
       rect.height = rect.height + 25;
       
       Grilla.clearSelection();
       
       
       
      
    try {
         BufferedImage captureImage = new BufferedImage(rect.width, rect.height,BufferedImage.TYPE_INT_ARGB);
        jPanel6.paint(captureImage.getGraphics());
        
        // Recoge el Clipboard del sistema.
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        // Construye un Transferable con la imagen
        ImageSelection dh = new ImageSelection(captureImage);
        // Pone la imagen en el Clipboard
        cb.setContents(dh, null);
//        TableModel.removeRow(Grilla.getRowCount()-1);
     } catch (Exception ex) {
        System.err.println(ex);
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        TableModel.addRow(new Object[]{"", 
                                               "", 
                                               "TOTAL DEUDA",
                                               "",
                                               "",
                                               "", 
                                               "", 
                                               "", 
                                               "", 
                                               "",
                                               "",
                                               fmMain.FormatoTotal(Double.valueOf(fmMain.SetGuardar(lbSumMontos.getText()))),
                                               ""});
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MnuAbrirPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAbrirPDFActionPerformed
//          Ftp ftp = new Ftp();
          
//        String path = "\\\\192.168.0.130\\Documentos Electronicos";
//            String files;
//            File folder = new File(path);
//            File[] listOfFiles = folder.listFiles(new FilenameFilter() {
//                @Override
//                public boolean accept(File folder, String Nombre) {
//                    return Nombre.contains("33F" + Grilla.getValueAt(Grilla.getSelectedRow(),5).toString().toString());
//                }
//            });
//            for (int i = 0; i < listOfFiles.length; i++)         {
//
//            if (listOfFiles[i].isFile())             {
//                
//                files = listOfFiles[i].getName();
//                try {
//                    File pathCompleto = new File(path + "\\" +files);
//                    Desktop.getDesktop().open(pathCompleto);
//                } catch (IOException ex) {
//                    ex.printStackTrace();
//                }
//            }
//        }
        busca("33", Grilla.getValueAt(Grilla.getSelectedRow(),5).toString().trim());
    }//GEN-LAST:event_MnuAbrirPDFActionPerformed

    
//      public void busca(String tip, String num){
//    
//    ExeSql Sql = new ExeSql();
//        ResultSet Rs;
//        String Query="";
//        String path;
//        String server,user,pass,ruta_local="";
//        int puerto =21;
//        String rutaimage="";
//        String filtro="";
//        String archivo_local = "";
//     
//try {
//
//           final String Tipo;
//           final String Numero;
//           int cont =0; 
//            
//              
//            Tipo=tip;
//            Numero= num;
//            
////---------                     Trae Datos Ftp            ----------------------
////Creado por CRM - 15-06-2017            
// //trae datos ftp
//            server="";
//            puerto=0;
//            user=""; 
//            pass="";
//            	Rs = Sql.Select("SELECT * from conexiones where tipo='ftp_dte'");
//                if (Rs.next())
//                {
//                    server = Rs.getString("serv");
//                    user  = Rs.getString("usu");
//                    puerto  = Rs.getInt("port");
//                    pass = Rs.getString("pass");
//                }
//              
////                  //Verifica SO
//                    String sistema = System.getProperty("os.name").toLowerCase();
//                    File folder = new File("");
//                    if (sistema.contains("win"))
//                    {
//                         ruta_local = "c:/" + carpeta + "/";
//                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
//                    }
//                    else{
//                          ruta_local = "/" + carpeta + "/";
//                          folder = new File(ruta_local);
//                    }
//                    if (!folder.exists())
//                    {
//                        folder.mkdir();
//                    }
//                    
//                     System.out.println("Carpeta Asignada " + ruta_local );
//            
//                    // Primer buscara el archivo en ruta local
//                    filtro = Tipo + "F" + Numero + ".pdf";
//                    System.out.println("Busca en carpeta  local" + ruta_local +"/"+filtro );
//                    archivo_local = BuscaArchivos(new File(ruta_local),filtro);
//                    System.out.println("Busca archivo en FTP -->" + ruta_local +"/"+filtro );
//                    Ftp.busca_archivo_ftp(server, puerto, user, pass, ruta_local,archivo_local, filtro);
//                    System.out.println("Sale de Busca Archivo" + filtro );
//                        }
//catch (Exception e) {
//            fmMain.Mensaje("Existe una inconsistencia en la información.");
//        }finally{
//            Sql.Close();
//        }
//}
    
    
    private void chkAutorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAutorizacionActionPerformed
        if (!chkAutorizacion.isSelected())
        {
            rbRutTodos.doClick();
            btBuscar.doClick();
        }
    }//GEN-LAST:event_chkAutorizacionActionPerformed

    private void txSkuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
            Grilla.setRowSorter(sorter);
            String sku = txSku.getText().trim();
            if (sku.length()==0)
            {
                sorter.setRowFilter(null);
            }
            else{
                int cant=0;
                int ev=0;
                String precio = "";
                sorter.setRowFilter(RowFilter.regexFilter(sku));
            }
        }
    }//GEN-LAST:event_txSkuKeyPressed

    private void txSkuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyReleased
        TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(Grilla.getModel());
        Grilla.setRowSorter(sorter);
        String sku = txSku.getText().trim();
        if (sku.length()==0)
        {
            sorter.setRowFilter(null);
        }
        else{
            int cant=0;
            int ev=0;
            String precio = "";
            sorter.setRowFilter(RowFilter.regexFilter(sku));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txSkuKeyReleased

    private void txSkuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSkuKeyTyped
        // TODO add your handling code here:
        if (Character.isLowerCase(evt.getKeyChar()))
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txSkuKeyTyped

    private void rbFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFacturasActionPerformed

    private void rbDocTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDocTodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDocTodasActionPerformed
public void CargaCliente(String Rut){
    ExeSql  Sql = new ExeSql();
    ResultSet Rs;
    
    try{
        Rs = Sql.Select("select rut,dv,nombre\n" +
                        "from cliente\n" +
                        "where rut=" + Rut);
    
        if(Sql.GetRowCount()==0){
            fmMain.Mensaje("Rut no encontrado");
            return;
        }
        Rs.next();
        txRut.setText(Rs.getString("Rut"));
        txCliente.setText(Rs.getString("nombre").trim());
        /*
        Carga Codigo_Oc
        */
        cbCodigo_Oc.removeAllItems();
        Rs = Sql.Select("select codigo_oc\n" +
                        "from clicontacto\n" +
                        "where rut=" + Rut);
        while(Rs.next()){
            cbCodigo_Oc.addItem(Rs.getString("codigo_oc").trim());
        }
        cbCodigo_Oc.addItem("Todos");

    } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally{
        Sql.Close();
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JTable GrillaBlog;
    private javax.swing.JMenuItem MnuAbrirPDF;
    private javax.swing.JButton btAgregarBlog;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEliminaBlog;
    private javax.swing.JButton btEmail;
    private javax.swing.JButton btIr;
    private javax.swing.JButton btPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox cbCodigo_Oc;
    public javax.swing.JCheckBox chkAutorizacion;
    private javax.swing.JCheckBox chkBloqueos;
    private javax.swing.JCheckBox chkContactos;
    private javax.swing.JCheckBox chkPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbContPagos;
    private javax.swing.JLabel lbSumDeuda;
    private javax.swing.JLabel lbSumMontos;
    private javax.swing.JLabel lbSumPagado;
    private javax.swing.JLabel lbSumSeleccionDeuda;
    private javax.swing.JLabel lbSumSeleccionMonto;
    private javax.swing.JLabel lbSumSeleccionPagado;
    private javax.swing.JLabel lbcargando;
    private javax.swing.JRadioButton rbBoletas;
    private javax.swing.JRadioButton rbDocTodas;
    private javax.swing.JRadioButton rbFacturas;
    private javax.swing.JRadioButton rbMonto;
    private javax.swing.JRadioButton rbMontoTodos;
    private javax.swing.JRadioButton rbPagadas;
    private javax.swing.JRadioButton rbRut;
    private javax.swing.JRadioButton rbRutTodos;
    private javax.swing.JRadioButton rbTodas;
    private javax.swing.JRadioButton rbVencidas;
    private javax.swing.JRadioButton rbVigentes;
    private javax.swing.JTextField txCliente;
    private javax.swing.JTextField txCodigo_Oc;
    private javax.swing.JTextField txContacto;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txFono;
    private javax.swing.JTextField txMonto;
    private javax.swing.JTextField txRut;
    private javax.swing.JTextField txRutBlog;
    private javax.swing.JTextField txSku;
    // End of variables declaration//GEN-END:variables
}
