/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdAgregaDato;
import Dialogos.jdGastoNuevo;
import Formularios.fmMain;
import java.sql.ResultSet;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Alcaman
 */
public class pfGastosConfig extends javax.swing.JPanel {

    /**
     * Creates new form pfGastosConfig
     */
    public pfGastosConfig() {
        initComponents();
        CargaGastos();
        GrillaGastos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(GrillaGastos.getSelectedRowCount()>0)
                    CargaGastosDetalles();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GrillaGastos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txCtaContable = new javax.swing.JTextField();
        btCtaContable = new javax.swing.JButton();
        txCtaContableCod = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        GrillaCCostos = new javax.swing.JTable();
        btAgregarCCosto = new javax.swing.JButton();
        btEliminarCCosto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chkSinRut = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txComentarios = new javax.swing.JTextArea();
        btAgregaGasto = new javax.swing.JButton();
        chkVigente = new javax.swing.JCheckBox();

        pnMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("CONFIGURACIÓN DE GASTOS");

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        GrillaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "GASTOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GrillaGastos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(GrillaGastos);
        if (GrillaGastos.getColumnModel().getColumnCount() > 0) {
            GrillaGastos.getColumnModel().getColumn(0).setMinWidth(0);
            GrillaGastos.getColumnModel().getColumn(0).setPreferredWidth(0);
            GrillaGastos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setText("Cuenta Contable");

        btCtaContable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos22/Go.png"))); // NOI18N
        btCtaContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCtaContableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txCtaContableCod, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txCtaContableCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txCtaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "CENTRO DE COSTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10))); // NOI18N

        GrillaCCostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CENTRO DE COSTOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(GrillaCCostos);
        if (GrillaCCostos.getColumnModel().getColumnCount() > 0) {
            GrillaCCostos.getColumnModel().getColumn(0).setMinWidth(0);
            GrillaCCostos.getColumnModel().getColumn(0).setPreferredWidth(0);
            GrillaCCostos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btAgregarCCosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btAgregarCCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCCostoActionPerformed(evt);
            }
        });

        btEliminarCCosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Cancel16.png"))); // NOI18N
        btEliminarCCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarCCostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btAgregarCCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEliminarCCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAgregarCCosto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btEliminarCCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Otras Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chkSinRut.setText("Proveedor General");
        chkSinRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSinRutActionPerformed(evt);
            }
        });

        jLabel3.setText("Observaciones");

        txComentarios.setColumns(20);
        txComentarios.setRows(5);
        jScrollPane1.setViewportView(txComentarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSinRut)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkSinRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(158, 158, 158)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        btAgregaGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/Agregar.png"))); // NOI18N
        btAgregaGasto.setText("Agregar");
        btAgregaGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregaGastoActionPerformed(evt);
            }
        });

        chkVigente.setText("Vigente");
        chkVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVigenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAgregaGasto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkVigente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAgregaGasto)
                            .addComponent(chkVigente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarCCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCCostoActionPerformed
        String Query="";
        String Codigos = "";

        if(GrillaCCostos.getRowCount()==0)
        Query = "select id as codigo, nombre\n" +
        "from pccostos";
        else{
            for(int i=0; i< GrillaCCostos.getRowCount();i++){
                Codigos = Codigos + GrillaCCostos.getValueAt(i,0).toString().trim() + ",";
            }
            if(Codigos.length()>0)
            Codigos = Codigos.substring(0, Codigos.length()-1);
            Query = "select id as codigo,nombre\n" +
                    "from pccostos where id not in ("+ Codigos +")";
        }        // TODO add your handling code here:

        jdAgregaDato Dato = new jdAgregaDato(null, true);
        Dato.setLocationRelativeTo(null);
        Dato.setTitle("Asocia C. Costos");
        Dato.CargaDatos(Query);
        Dato.setVisible(true);
        if(!Dato.GetCodigo().isEmpty()){
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("insert into gastos_link (ccosto,gastosdet) values (" + Dato.GetCodigo() + "," + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(),0).toString().trim() + ")");
                Sql.Commit();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }finally{
                Sql.Close();
                CargaCCostos();
            }

        }
    }//GEN-LAST:event_btAgregarCCostoActionPerformed

    private void btCtaContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCtaContableActionPerformed
        String Query="";
        
        Query = "select codigo,nombre\n" +
                "from conta_plan\n" +
                "where codigo like '3%'\n" +
                "and codigo not like '30%' and nivel=4 order by nombre";
        
        jdAgregaDato Dato = new jdAgregaDato(null, true);
        Dato.setLocationRelativeTo(null);
        Dato.setTitle("Cuenta Contable");
        Dato.CargaDatos(Query);
        Dato.setVisible(true);
        
        if(!Dato.GetCodigo().isEmpty()){
            ExeSql Sql = new ExeSql();
            try {
                Sql.ExeSql("update gastos_det\n" +
                           "set cuenta='"+ Dato.GetCodigo().trim() +"'\n" +
                           "where id=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(), 0).toString().trim());
                Sql.Commit();
                txCtaContableCod.setText(Dato.GetCodigo().trim());
                txCtaContable.setText(Dato.GetNombre().trim());
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }finally{
                Sql.Close();
            }

        }
    }//GEN-LAST:event_btCtaContableActionPerformed

    private void btEliminarCCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarCCostoActionPerformed
        ExeSql Sql = new ExeSql();
        try {
            Sql.ExeSql("delete from gastos_link where ccosto=" + GrillaCCostos.getValueAt(GrillaCCostos.getSelectedRow(), 0).toString() + " and gastosdet=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(),0).toString());
            Sql.Commit();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally{
            Sql.Close();
            CargaCCostos();
        }
    }//GEN-LAST:event_btEliminarCCostoActionPerformed

    private void chkSinRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSinRutActionPerformed
        ExeSql Sql = new ExeSql();
        try {
            Sql.ExeSql("update gastos_det set sinrut=" + chkSinRut.isSelected() + " where id=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(),0).toString().trim());
            Sql.Commit();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Sql.Rollback();
        }finally{
            Sql.Close();
        }
    }//GEN-LAST:event_chkSinRutActionPerformed

    private void btAgregaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregaGastoActionPerformed
        jdGastoNuevo NuevoGasto = new jdGastoNuevo(null, true);
        NuevoGasto.setTitle("Nuevo Gasto");
        NuevoGasto.CargaTipos("TIPO_GASTOS");
        NuevoGasto.setLocationRelativeTo(null);
        NuevoGasto.setVisible(true);
        
        CargaGastos();
               
    }//GEN-LAST:event_btAgregaGastoActionPerformed

    private void chkVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVigenteActionPerformed
        if(GrillaGastos.getSelectedRowCount()>0){
            ExeSql Sql = new ExeSql();
            
            try {
                Sql.ExeSql("update gastos_det set vigente=" + chkVigente.isSelected() + " where id=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(),0).toString().trim());
                Sql.Commit();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                Sql.Rollback();
            }
            finally{
                Sql.Close();
            }
        }
    }//GEN-LAST:event_chkVigenteActionPerformed
    private void CargaGastosDetalles(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaCCostos.getModel();
        
        fmMain.LimpiaGrilla(Model);
        
        try {
            CargaCCostos();
            //Carga Cuenta Contable y detalles
            Rs = Sql.Select("select p.codigo,p.nombre, d.sinrut,d.comentarios,vigente\n" +
                            "from gastos_det d\n" +
                            "join conta_plan p on d.cuenta=p.codigo\n" +
                            "where d.id=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(),0).toString().trim());
            if(Sql.GetRowCount()>0){
                Rs.next();
                txCtaContableCod.setText(Rs.getString("codigo").trim());
                txCtaContable.setText(Rs.getString("nombre").trim());
                chkSinRut.setSelected(Rs.getBoolean("sinrut"));
                chkVigente.setSelected(Rs.getBoolean("vigente"));
                txComentarios.setText(Rs.getString("comentarios").trim());
            }
            else{
                txCtaContableCod.setText("");
                txCtaContable.setText("");
            }
            
            
        } catch (Exception e) {
        }finally{
            Sql.Close();
        }
        
        
    }
    private void CargaCCostos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaCCostos.getModel();
        
        fmMain.LimpiaGrilla(Model);
        
        try {
            Rs = Sql.Select("select cc.id, cc.nombre\n" +
                            "from gastos_link l\n" +
                            "left join pccostos cc on l.ccosto=cc.id\n" +
                            "where l.gastosdet=" + GrillaGastos.getValueAt(GrillaGastos.getSelectedRow(), 0).toString().trim());
            while(Rs.next()){
                Model.addRow(new Object[]{
                            Rs.getString("id").trim(),
                            Rs.getString("nombre").trim()
                });
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }
    private void CargaGastos(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        DefaultTableModel Model = (DefaultTableModel) GrillaGastos.getModel();
        
        fmMain.LimpiaGrilla(Model);
        
        try {
            Rs = Sql.Select("select id,nombre\n" +
                            "from gastos_det order by nombre");
            while(Rs.next()){
                Model.addRow(new Object[]{
                            Rs.getString("id").trim(),
                            Rs.getString("nombre").trim()
                });
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }finally{
            Sql.Close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GrillaCCostos;
    private javax.swing.JTable GrillaGastos;
    private javax.swing.JButton btAgregaGasto;
    private javax.swing.JButton btAgregarCCosto;
    private javax.swing.JButton btCtaContable;
    private javax.swing.JButton btEliminarCCosto;
    private javax.swing.JCheckBox chkSinRut;
    private javax.swing.JCheckBox chkVigente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JTextArea txComentarios;
    private javax.swing.JTextField txCtaContable;
    private javax.swing.JTextField txCtaContableCod;
    // End of variables declaration//GEN-END:variables
}
