/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;
import Conexion.Conector;
import Conexion.ExeSql;
import Dialogos.jdAbrirOCCDirecto;
import Dialogos.jdAddDatosPersona;
import Dialogos.jdBuscarCliPrv;
import Dialogos.jdBuscarProductos;
import Dialogos.jdCCLAgregaProducto;
import Dialogos.jdDiasOCP;
import Dialogos.jdIngresaNumero;
import Dialogos.jdIngresaPrecios_Catalogo;
import Dialogos.jdQuienFirmaCot;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import static PanelForm.pfBuscaDoc.BuscaArchivos;
import static PanelForm.pfGDCliente.GetCol;
import Utilidades.ComboCodigos;
import static Utilidades.DocElect.carpeta;
import Utilidades.Ftp;
import Utilidades.ListarProductos;
import Utilidades.PanelTab;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.compilers.JRGroovyCompiler;

/**
 *
 * @author MauricioLuvaly
 */
public class pfGenerarCatalogoRespaldo extends javax.swing.JPanel {

    int Tipo=-1; //-1 Nada de nada      1 Nuevo      2 Abierto      3.Editando
    private boolean Retorno;
    public String imagenProducto;
    int id_doc;
    /**
     * Creates new form pfGenerarCatalogo
     */
    public pfGenerarCatalogoRespaldo() {
        initComponents();
        btEditar.setEnabled(false);
        btCancelar.setEnabled(false);
        btGuardar.setEnabled(false);
        txTitulo.setEnabled(false);
        txSubtitulo.setEnabled(false);
        txCodigoProducto.setEnabled(false);
        btAgregarProducto.setEnabled(false);
        btBuscarCodigo.setEnabled(false);
        txNombre.setEnabled(false);
        txCodigoCC.setEnabled(false);
        txUnidad.setEnabled(false);
        txPrecioReal.setEnabled(false);
        txPrecioOferta.setEnabled(false);
        btGenerarCatalogo.setEnabled(false);
        txIdCatalogo.setEnabled(true);
        lbImagen.setVisible(false);
        txIdCatalogo.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txSubtitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txCodigoProducto = new javax.swing.JTextField();
        btBuscarCodigo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txPrecioReal = new javax.swing.JTextField();
        btAgregarProducto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txUnidad = new javax.swing.JTextField();
        lbUnidad = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txCodigoCC = new javax.swing.JTextField();
        lbUM = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txPrecioOferta = new javax.swing.JTextField();
        lbImagen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btAbrirDoc = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txIdCatalogo = new javax.swing.JTextField();
        btGenerarCatalogo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        btEliminaBulto1 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Título Catálogo:");

        jLabel2.setText("Subtitulo:");

        jLabel3.setText("Código Producto");

        btBuscarCodigo.setText("Buscar Producto");
        btBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCodigoActionPerformed(evt);
            }
        });

        jLabel5.setText("Precio Real");

        btAgregarProducto.setText("Agregar Producto");
        btAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProductoActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Producto");

        jLabel6.setText("Unidad de medida");

        jLabel8.setText("Código Chile Compras");

        jLabel9.setText("Precio Oferta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCodigoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbUM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPrecioReal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAgregarProducto)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbUnidad)
                                .addGap(320, 320, 320))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarCodigo)
                    .addComponent(jLabel7)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUnidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txCodigoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txPrecioReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAgregarProducto)
                        .addComponent(jLabel9)
                        .addComponent(txPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btAbrirDoc.setText("Abrir Documento");
        btAbrirDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirDocActionPerformed(evt);
            }
        });

        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel10.setText("ID CATÁLOGO:");

        txIdCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdCatalogoActionPerformed(evt);
            }
        });
        txIdCatalogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txIdCatalogoKeyPressed(evt);
            }
        });

        btGenerarCatalogo.setText("GENERAR CÁTALOGO");
        btGenerarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarCatalogoActionPerformed(evt);
            }
        });

        jButton1.setText("Catalogo ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAbrirDoc)
                .addGap(18, 18, 18)
                .addComponent(btNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGuardar)
                .addGap(182, 182, 182)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txIdCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGenerarCatalogo)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAbrirDoc)
                    .addComponent(btNuevo)
                    .addComponent(btCancelar)
                    .addComponent(btEditar)
                    .addComponent(btGuardar))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txIdCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGenerarCatalogo)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PRODUCTOS");

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "sku", "Nombre", "Precio Real", "Precio Oferta", "UM", "Imagen Windows", "Imagen Linux", "SKU", "Nombre", "Codigo CC", "Unidades", " Precio Real", " Precio Oferta", "Mod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(100);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(1).setMinWidth(120);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(120);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(120);
            Grilla.getColumnModel().getColumn(2).setMinWidth(300);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(300);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(300);
            Grilla.getColumnModel().getColumn(3).setMinWidth(100);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(4).setMinWidth(100);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(5).setMinWidth(70);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(70);
            Grilla.getColumnModel().getColumn(6).setMinWidth(0);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(7).setMinWidth(0);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(0);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(0);
            Grilla.getColumnModel().getColumn(8).setMinWidth(50);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(50);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(50);
            Grilla.getColumnModel().getColumn(9).setMinWidth(60);
            Grilla.getColumnModel().getColumn(9).setPreferredWidth(60);
            Grilla.getColumnModel().getColumn(9).setMaxWidth(60);
            Grilla.getColumnModel().getColumn(10).setMinWidth(85);
            Grilla.getColumnModel().getColumn(10).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(10).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(11).setPreferredWidth(70);
            Grilla.getColumnModel().getColumn(12).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(13).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(14).setResizable(false);
            Grilla.getColumnModel().getColumn(14).setPreferredWidth(0);
        }

        btEliminaBulto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos16/trush16.png"))); // NOI18N
        btEliminaBulto1.setText("Elimina");
        btEliminaBulto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaBulto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btEliminaBulto1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEliminaBulto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SetTipo(int ElTipo){
    if(ElTipo==-1){
        fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),0);
        Tipo = -1;
        Habilita(false);
        Edicion(false);
    }
    //Nuevo Producto
        else if(ElTipo==1){
        fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),1);    
        Tipo = 1;
        Habilita(true);
        Edicion(true);
        }
    //Abre Producto
        else if (ElTipo==2){
         fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),0);   
        Tipo = 2;
        }
    else if(ElTipo==3){
        fmMain.SetEstado(fmMain.pnPestanas.getSelectedIndex(),1);
        Tipo = 3;
        }
    }
    
    public void Setea_numero(){
        txIdCatalogo.requestFocus();
    }
    
    private void Habilita(boolean Estado){
        btEditar.setEnabled(Estado);
        btCancelar.setEnabled(Estado);
        btGuardar.setEnabled(Estado);
        txTitulo.setEnabled(Estado);
        txSubtitulo.setEnabled(Estado);
        txCodigoProducto.setEnabled(Estado);
        btAgregarProducto.setEnabled(Estado);
        txPrecioReal.setEnabled(Estado);
        btBuscarCodigo.setEnabled(Estado);
        txCodigoCC.setEnabled(Estado);
        txUnidad.setEnabled(Estado);
        txPrecioOferta.setEnabled(Estado);
        txNombre.setEnabled(Estado);
        
    }
    
    private void Edicion(boolean Estado){
        btEditar.setEnabled(Estado);
        btCancelar.setEnabled(Estado);
        btGuardar.setEnabled(Estado);
        txTitulo.setEnabled(Estado);
        txSubtitulo.setEnabled(Estado);
        txCodigoProducto.setEnabled(Estado);
        btAgregarProducto.setEnabled(Estado);
        txPrecioReal.setEnabled(Estado);
        btBuscarCodigo.setEnabled(Estado);
    }
    
    private void btBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCodigoActionPerformed
        txUnidad.setText("");
        lbUnidad.setText("");
        txPrecioReal.setText("");
        buscarProducto();
    }//GEN-LAST:event_btBuscarCodigoActionPerformed

    private void btAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProductoActionPerformed
        DefaultTableModel tbModel = (DefaultTableModel) Grilla.getModel();       
        String bsku, bNombre, bCodigoCC, bUnidades, bPrecioReal, bPrecioOferta;
        
        if (txCodigoProducto.getText().equals("")){
            fmMain.Mensaje("Debe ingresar un codigo");
            txCodigoProducto.requestFocus();
            return;      
        }
        
        if (txPrecioReal.getText().equals("")){
            fmMain.Mensaje("Debe ingresar Precio Real.");
            txPrecioReal.requestFocus();
            return;      
        }
        
        if (txPrecioOferta.getText().equals("")){
            fmMain.Mensaje("Debe ingresar un Precio Oferta.");
            txPrecioOferta.requestFocus();
            return;      
        }
        if(!ExisteEnGrilla(txCodigoProducto.getText())){
            tbModel.addRow(GetFilaCatalogo());
            Limpia();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "El producto ya esta en el listado");
        }

    }//GEN-LAST:event_btAgregarProductoActionPerformed

    public void Limpia(){
        txCodigoProducto.setText("");
        txNombre.setText("");
        txCodigoCC.setText("");
        txUnidad.setText("");
        lbUM.setText("");
        txPrecioReal.setText("");
        txPrecioOferta.setText("");
        lbImagen.setText("");
    }
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        if (txTitulo.getText() == ("")){
        JOptionPane.showMessageDialog(null, "No dejar campos en blanco");
//             || (txSubtitulo.getText("")) || (txCodigoProducto.getText("")) || (txNombre.getText("")) || (txUnidad.getText("")) || (txPrecioOferta.getText("")) || (txPrecioReal.getText(""))
        }else{
        
        graba_catalogo();
        
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btGenerarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarCatalogoActionPerformed
     // TODO add your handling code here:
        buscaFoto();
        Conector con = new Conector();
        Connection conn = con.getConnection();
        String path = "/Reportes/Enca_Catalogo.jasper";//       Map parametro  = new HashMap();            
        URL in = this.getClass().getResource(path);
        JasperReport repo = null;
        HashMap<String, Object> parametros = new HashMap<>();
         parametros.put("id_catalogo",  Integer.valueOf(txIdCatalogo.getText()));
         
        try {
            repo = (JasperReport)JRLoader.loadObject(in);
            JasperPrint jprint = JasperFillManager.fillReport(repo, parametros,conn);
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
           
        } catch (JRException ex) {
            Logger.getLogger(pfGenerarCatalogoRespaldo.class.getName()).log(Level.SEVERE, null, ex);
        }        

         
    }//GEN-LAST:event_btGenerarCatalogoActionPerformed

    private void btAbrirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirDocActionPerformed
        SetTipo(2);
        btEditar.setEnabled(true);
        buscaCatalogo(txIdCatalogo.getText());
        btGenerarCatalogo.setEnabled(true);
    }//GEN-LAST:event_btAbrirDocActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        SetTipo(1);
        btEditar.setEnabled(false);
        btAbrirDoc.setEnabled(false);
        txIdCatalogo.setEnabled(false);
        btCancelar.setEnabled(true);
        Limpia();
        txTitulo.setText("");
        txSubtitulo.setText("");
        txIdCatalogo.setText("");
        btGenerarCatalogo.setEnabled(false);
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
       SetTipo(-1);
       btAbrirDoc.setEnabled(true);
       btNuevo.setEnabled(true);
       txIdCatalogo.setEnabled(true);
       Limpia();
       txTitulo.setText("");
       txSubtitulo.setText("");
       txIdCatalogo.setText("");
       reiniciarJTable(Grilla);
 
    }//GEN-LAST:event_btCancelarActionPerformed

    public static void reiniciarJTable(javax.swing.JTable Tabla){
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        while(modelo.getRowCount()>0)modelo.removeRow(0);
 
    }

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
       SetTipo(1);
       btAbrirDoc.setEnabled(false);
       btNuevo.setEnabled(false);
       txIdCatalogo.setEnabled(false);
    }//GEN-LAST:event_btEditarActionPerformed

    private void txIdCatalogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txIdCatalogoKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
             btAbrirDoc.doClick();
        }
    }//GEN-LAST:event_txIdCatalogoKeyPressed

    private void btEliminaBulto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaBulto1ActionPerformed
        // TODO add your handling code here:
        if(fmMain.OkCancel("¿Desea Eliminar?")== JOptionPane.OK_OPTION){
            DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
            ExeSql Sql = new ExeSql();
            ResultSet Rs;
            String Query, qryDel,G_Nombre ;
            String G_idSku;
            String Sku;

            try{
                G_idSku = Grilla.getValueAt(Grilla.getSelectedRow(), 1).toString();
                if (G_idSku.equals("")){
                    fmMain.Mensaje("No se puede Eliminar cuando se seleccionan todos los bultos");
                    return;
                }
                qryDel = "delete from catalogo_productos where id_catalogo = " + txIdCatalogo.getText().trim() + " and sku = '" + G_idSku + "';";
                Sql.ExeSql(qryDel);
                
                Sql.Commit();
                fmMain.Mensaje("Se ha eliminado correctamente el producto " + G_idSku  + " del catalogo " + txIdCatalogo.getText().trim()) ;

            }
            catch (Exception e) {
                System.out.println(e.getMessage());
                Sql.Rollback();
            } finally{
                Sql.Close();
            }
            fmMain.LimpiaGrilla(TableModel);
            btAbrirDoc.doClick();
        }
        
        
        
        
    }//GEN-LAST:event_btEliminaBulto1ActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        // TODO add your handling code here:
          if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(), 0).toString().isEmpty()){
            jdIngresaPrecios_Catalogo jdNumero = new jdIngresaPrecios_Catalogo(null, true);
            jdNumero.setLocationRelativeTo(null);
            jdNumero.setVisible(true);        
            if(jdNumero.GetNumero() != -99 ){
                Grilla.setValueAt(String.valueOf(jdNumero.GetPrecioReal()), Grilla.getSelectedRow(),3);
                Grilla.setValueAt(String.valueOf(jdNumero.GetPrecioOferta()), Grilla.getSelectedRow(),4);
            }
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void txIdCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdCatalogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        buscaFoto();
        Conector con = new Conector();
        Connection conn = con.getConnection();
        String path = "/Reportes/Enca_Catalogo2.jasper";//       Map parametro  = new HashMap();            
        URL in = this.getClass().getResource(path);
        JasperReport repo = null;
        HashMap<String, Object> parametros = new HashMap<>();
         parametros.put("id_catalogo",  Integer.valueOf(txIdCatalogo.getText()));
         
        try {
            repo = (JasperReport)JRLoader.loadObject(in);
            JasperPrint jprint = JasperFillManager.fillReport(repo, parametros,conn);
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
           
        } catch (JRException ex) {
            Logger.getLogger(pfGenerarCatalogoRespaldo.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
//    private Connection coneccionSQL()
//     {
//            try
// 
//            {
// 
//                    String cadena;
// 
//                    cadena="jdbc:postgresql://192.168.0.150:5432/postgres";
// 
//                    Class.forName("org.postgresql.Driver");
// 
//                    Connection con = DriverManager.getConnection(cadena, "cramirez","luv1234");
// 
//                    return con;
// 
//            }
// 
//            catch(Exception e)
// 
//            {
// 
//                   System.out.println(e.getMessage());
// 
//            }
// 
//            return null;
// 
//    }
    
    
    public void abrirReporte(String ruta, Connection cnx, Map parametros){
//        try{
//            JasperReport report = JasperCompileManager.compileReport(ruta);
//            JasperPrint print = JasperFillManager.fillReport(report,parametros,cnx);
//            JasperViewer.viewReport(print,false);
//        }
//        catch (JRException jRException ){
//            System.err.println(jRException.getMessage());
//            JOptionPane.showMessageDialog(null, "Error al abrir Reporte");
//        }
        

    }
    
    public void buscaFoto(){
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        String server,user,pass,ruta_local="";
        int puerto =21;
        String rutaimage="";
        String sku ="";
        String skuBusca ="", Foto ="", Query = "", archivo ="";
        
        
        try {

//            server= "192.168.0.130";
//            user="voucher";
//            pass="V2369";   
            
           //trae datos ftp
            server="";
            puerto=0;
            user=""; 
            pass="";
            	Rs = Sql.Select("SELECT * from conexiones where usu='fotoproducto'");
                if (Rs.next())
                {
                    server = Rs.getString("serv");
                    user  = Rs.getString("usu");
                    puerto  = Rs.getInt("port");
                    pass = Rs.getString("pass");
                }
           //trae datos ftp
            
           for(int i=0; i< Grilla.getRowCount(); i++){
            skuBusca = Grilla.getValueAt(i, 1).toString();
            Rs = Sql.Select("SELECT imagen, sku from producto where sku='"+skuBusca+"';");
            Rs.next();
            if (Rs.getInt("sku")>=1)
            {
                if (sku.equals("")){
                    sku = Rs.getString("sku");
                }                    
                Rs = Sql.Select("SELECT imagen, sku from producto where sku='"+skuBusca+"';");
                Rs.next();
                if (Rs.getString("imagen") != null)
                {
                    rutaimage=Rs.getString("imagen");
                     Foto = "c:\\fotosproductos\\" + fmMain.GetStringDeFinal('\\', rutaimage);
                     Query = "update catalogo_productos set imagen_windows = '" + Foto + "' where id_catalogo = " + txIdCatalogo.getText().trim() +
                            " and sku = '" + skuBusca + "'";
                    Sql.ExeSql(Query);
                } 
                else
                {
                    rutaimage="\\\\192.168.0.130\\fotosproductos\\SinImagen.png";
                    // Updatear la imagen a Sin Imagen
                    // String Query = "update catalogo_productos set imagen_windows = '\\\\192.168.0.130\\fotosproductos\\SinImagen.png' where id_catalogo = " + txIdCatalogo.getText().trim() +
                    //        " and sku = '" + skuBusca + "'";
                     Query = "update catalogo_productos set imagen_windows = 'c:\\fotosproductos\\SinImagen.png' where id_catalogo = " + txIdCatalogo.getText().trim() +
                            " and sku = '" + skuBusca + "'";
                    Sql.ExeSql(Query);
                    
                }
                
                    //Verifica SO
                    String sistema = System.getProperty("os.name").toLowerCase();
                    File folder = new File("");
                    if (sistema.contains("win"))
                    {
                         ruta_local = "c:/fotosproductos/";
                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
                    }
                    else{
                          ruta_local = "/fotosproductos/";
                          folder = new File(ruta_local);
                    }
                    if (!folder.exists())
                    {
                        folder.mkdir();
                    }
                    
                    //rutaimage=Rs.getString("imagen");
                    //String archivo = rutaimage.substring(35,rutaimage.length());
                    
                    archivo = fmMain.GetStringDeFinal('\\', rutaimage);
                    Ftp.baja_archivo_ftp(server, puerto,user, pass,"/"+archivo,ruta_local + archivo);
                    
                    
                     File file = new File(ruta_local+archivo);
            }
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        finally{
            Sql.Close();
            
        }
    }
   
   
    
    public void buscaCatalogo(String NumeroCTC ){
    ExeSql Sql = new ExeSql();
    ExeSql Sql1 = new ExeSql();
    ResultSet Rs,Rs1;
    String Query="", QryVend="";
    DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
     //NumeroCTC = txIdCatalogo.getText();
    
    fmMain.LimpiaGrilla(TableModel);
    
    try{
     Query = "SELECT c.titulo_catalogo,\n" +
             "       c.subtitulo_catalogo,\n" +
             "       p.sku,\n" +
             "       p.nombre,\n" +
             "       p.codigo_cc,\n" +
             "       p.unidad,\n" +
             "       p.precio_real,\n" +
             "       p.precio_oferta,\n" +
             "       p.imagen_windows,\n" +
             "       p.imagen_linux,\n" +
             "       p.bsku,\n" +
             "       p.bnombre,\n" +
             "       p.bcodigo_cc,\n" +
             "       p.bunidad,\n" +
             "       p.bprecio_real,\n" +
             "       p.bprecio_oferta\n" +
             "FROM catalogo c, catalogo_productos p\n" +
             "WHERE c.id_catalogo = "+NumeroCTC+ " AND\n" +
             "      c.id_catalogo = p.id_catalogo;";
     
        Rs = Sql.Select(Query);
        while(Rs.next()){
                txTitulo.setText(Rs.getString("titulo_catalogo"));
                txSubtitulo.setText(Rs.getString("subtitulo_catalogo"));
                TableModel.addRow(new Object[]{ Rs.getString("codigo_cc").trim(),
                                                Rs.getString("sku").trim(), 
                                                Rs.getString("nombre").trim(),                                               
                                                Rs.getInt("precio_real"),       
                                                Rs.getInt("precio_oferta"),
                                                Rs.getString("unidad").trim(),
                                                Rs.getString("imagen_windows").trim(),
                                                Rs.getString("imagen_linux").trim(),
                                                Rs.getBoolean("bsku"),
                                                Rs.getBoolean("bnombre"),
                                                Rs.getBoolean("bcodigo_cc"),
                                                Rs.getBoolean("bunidad"),
                                                Rs.getBoolean("bprecio_real"),
                                                Rs.getBoolean("bprecio_oferta"),
                                                "U"
                                                });
                
            }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error");
    }finally{
        Sql.Close();
    }
    }    
    
    
     public void  graba_catalogo(){
        ExeSql Sql = new ExeSql();
        ExeSql SqlBusca = new ExeSql();
        ResultSet RsBusca;
        ResultSet Rs;
        String Query;
        String QueryBuscaId;
        String Codigos="";
        String NewCorrelativo;
        String titulo, subtitulo, sku, id_catalogo, id_generado, nombre_producto, codigo_cc, unidad, precio_real, precio_oferta;
        String bsku, bnombre;
        String bunidad, bprecio_real, bprecio_oferta;
        String bcodigo_cc ,imagen,Modo;
        
        
        if(Tipo==1){
          
            try{
                if (txIdCatalogo.getText().equals("")){
                titulo = txTitulo.getText();
                subtitulo = txSubtitulo.getText();
                
                Sql.ExeSql("update par_correlativo set  numero = numero + 1 where tipo='CTC';");
                NewCorrelativo = Sql.SelectUnico("select numero from par_correlativo where tipo='CTC';");
                Sql.ExeSql("INSERT INTO catalogo (titulo_catalogo, subtitulo_catalogo, id_correlativo) VALUES ('"+titulo+"','"+subtitulo+"','"+NewCorrelativo+"');"); 
   

                QueryBuscaId = ("SELECT id_catalogo FROM catalogo WHERE id_correlativo ='"+NewCorrelativo+"';");
                RsBusca = Sql.Select(QueryBuscaId);
                RsBusca.next();
                txIdCatalogo.setText(RsBusca.getString("id_catalogo"));
               
                    for(int i=0; i< Grilla.getRowCount(); i++){
                    sku = Grilla.getValueAt(i, 1).toString();
                    id_catalogo = txIdCatalogo.getText();
                    id_generado = sku + id_catalogo;
                    nombre_producto = Grilla.getValueAt(i, 2).toString();
                    codigo_cc = Grilla.getValueAt(i, 0).toString();
                    unidad = Grilla.getValueAt(i, 5).toString();
                    precio_real = Grilla.getValueAt(i, 3).toString();
                    precio_oferta = Grilla.getValueAt(i, 4).toString();
                    
                    
                    
                    if (Grilla.getValueAt(i, 8)==null){
                        bsku = "false";
                    }
                    else
                    {
                        bsku = Grilla.getValueAt(i, 8).toString();
                    }
                    
                    if (Grilla.getValueAt(i, 9)==null){
                        bnombre = "false";
                    }
                    else
                    {
                        bnombre =  Grilla.getValueAt(i, 9).toString();
                    }
                    
                    
                   if (Grilla.getValueAt(i, 10)==null){
                        bcodigo_cc = "false";
                    }
                    else
                    {
                         bcodigo_cc = Grilla.getValueAt(i, 10).toString();
                    }
                    
                    
                   
                   if (Grilla.getValueAt(i, 11)==null){
                        bunidad = "false";
                    }
                    else
                    {
                         bunidad = Grilla.getValueAt(i, 11).toString();
                    }
                   
                   
                   if (Grilla.getValueAt(i, 12)==null){
                        bprecio_real = "false";
                    }
                    else
                    {
                         bprecio_real = Grilla.getValueAt(i, 12).toString();
                    }
                   
                    
                   if (Grilla.getValueAt(i, 13)==null){
                        bprecio_oferta = "false";
                    }
                    else
                    {
                         bprecio_oferta =  Grilla.getValueAt(i, 13).toString(); 
                    }
                    
                    
                    Query = "INSERT INTO catalogo_productos (id_generado, sku, id_catalogo, nombre, codigo_cc,\n" +
                            " unidad, precio_real, precio_oferta, bsku, bnombre, bcodigo_cc, bunidad,\n" +
                            "  bprecio_real, bprecio_oferta, imagen_windows, imagen_linux)\n" +
                            "VALUES ('"+id_generado+"','"+sku+"','"+id_catalogo+"','"+nombre_producto+"','"+codigo_cc+"','"+unidad+"','"+precio_real+"','"+precio_oferta+"',\n" +
                            "'"+bsku+"','"+bnombre+"','"+bcodigo_cc+"','"+bunidad+"','"+bprecio_real+"','"+bprecio_oferta+"','C:\\fotosproductos\\"+sku+".png', '/fotosproductos/"+sku+".png');";
                   
                    Sql.ExeSql(Query);
                    }
             }else{
                Sql.ExeSql("update catalogo set  titulo_catalogo = '"+txTitulo.getText()+"', subtitulo_catalogo = '"+txSubtitulo.getText()+"' where id_catalogo='"+txIdCatalogo.getText()+"'");  
                for(int j=0; j< Grilla.getRowCount(); j++){
                    sku = Grilla.getValueAt(j, 1).toString();
                    id_catalogo = txIdCatalogo.getText();
                    id_generado = sku + id_catalogo;
                    nombre_producto = Grilla.getValueAt(j, 2).toString();
                    codigo_cc = Grilla.getValueAt(j, 0).toString();
                    unidad = Grilla.getValueAt(j, 5).toString();
                    precio_real = Grilla.getValueAt(j, 3).toString();
                    precio_oferta = Grilla.getValueAt(j, 4).toString();
                    
                    
                    if (Grilla.getValueAt(j, 8) == null){
                        bsku = "false";
                    }
                    else{
                        bsku = Grilla.getValueAt(j, 8).toString();
                    }
                    
                    if (Grilla.getValueAt(j, 9) == null){
                        bnombre = "false";
                    }
                    else{
                        bnombre = Grilla.getValueAt(j, 9).toString();
                    }
                    
                    if (Grilla.getValueAt(j, 10) == null){
                        bcodigo_cc = "false";
                    }
                    else{
                        bcodigo_cc = Grilla.getValueAt(j, 10).toString();
                    }
                    
                    
                    if (Grilla.getValueAt(j, 11) == null){
                        bunidad = "false";
                    }
                    else{
                        bunidad = Grilla.getValueAt(j, 11).toString();
                    }
                    
                    if (Grilla.getValueAt(j, 12) == null){
                        bprecio_real = "false";
                    }
                    else{
                        bprecio_real = Grilla.getValueAt(j, 12).toString();
                    }
                    
                    if (Grilla.getValueAt(j, 13) == null){
                        bprecio_oferta = "false";
                    }
                    else{
                        bprecio_oferta = Grilla.getValueAt(j, 13).toString(); 
                    }
                    
                    if (Grilla.getValueAt(j, 14) == null){
                        Modo = "I";
                    }
                    else{
                        Modo = Grilla.getValueAt(j, 14).toString(); 
                    }
                    
                    
                
                    if(Modo.equals("U"))
                    {
                    Query = "UPDATE catalogo_productos\n" +
                            "SET sku = '"+sku+"',\n" +
                            "    nombre = '"+nombre_producto+"',\n" +
                            "    codigo_cc =  '"+codigo_cc+"',\n" +
                            "    unidad = '"+unidad+"',\n" +
                            "    precio_real = '"+precio_real+"',\n" +
                            "    precio_oferta = '"+precio_oferta+"',\n" +
                            "    bsku = "+bsku+",\n" +
                            "    bnombre = "+bnombre+",\n" +
                            "    bcodigo_cc = "+bcodigo_cc+",\n" +
                            "    bunidad = "+bunidad+",\n" +
                            "    bprecio_real = "+bprecio_real+",\n" +
                            "    bprecio_oferta = "+bprecio_oferta+" WHERE id_catalogo = '"+id_catalogo+"' and sku = '"+sku+"';";}
                    else
                    {
                           Query = "INSERT INTO catalogo_productos (id_generado, sku, id_catalogo, nombre, codigo_cc,\n" +
                            " unidad, precio_real, precio_oferta, bsku, bnombre, bcodigo_cc, bunidad,\n" +
                            "  bprecio_real, bprecio_oferta, imagen_windows, imagen_linux)\n" +
                            "VALUES ('"+id_generado+"','"+sku+"','"+id_catalogo+"','"+nombre_producto+"','"+codigo_cc+"','"+unidad+"','"+precio_real+"','"+precio_oferta+"',\n" +
                            "'"+bsku+"','"+bnombre+"','"+bcodigo_cc+"','"+bunidad+"','"+bprecio_real+"','"+bprecio_oferta+"','C:\\fotosproductos\\"+sku+".jpg', '/fotosproductos/"+sku+".jpg');"; 
                    }
                     Sql.ExeSql(Query);
                }
            }
                
             fmMain.Mensaje("CATÁLOGO REGISTRADO");
            }catch(Exception ex){
                    System.out.println(ex);
            }
        
        }
    }
    
   public Object[] GetFilaCatalogo(){  
     int Columna =14;
     int Fila = Grilla.getRowCount();
       if (txCodigoCC.getText().equals(null)){
           txCodigoCC.setText("");
       }
       return new Object[]{
                                txCodigoCC.getText(),
                                txCodigoProducto.getText(),
                                txNombre.getText(),
                                txPrecioReal.getText(),
                                txPrecioOferta.getText(),
                                lbUM.getText(),
                                lbImagen.getText()};  
    }
        
    public void buscarProducto(){
       String codbarfinal = txCodigoProducto.getText().replace("'", "-");
        txCodigoProducto.setText(codbarfinal.trim());
         if(!txCodigoProducto.getText().isEmpty()){
            txCodigoProducto.requestFocus();
         }
        else{
            jdBuscarProductos BP = new jdBuscarProductos(null, true);
            BP.setLocationRelativeTo(null);
            BP.setTitle("Buscar Producto");
            BP.setVisible(true);
            BP.SetCotiza(false); 
            if(!"".equals(BP.GetCodigo()))
                CargaProducto(BP.GetCodigo());
        }

    }
    
    public void CargaProducto(String Codigo){
    ExeSql Sql = new ExeSql();
    ResultSet Rs;
    
        try {

            Rs = Sql.Select("select p.sku,\n" +
                            "       p.nombre,\n" +
                            "       p.pventa,\n"+
                            "       p.imagen ,\n"+
                            "       p.codigo_cc,\n" +
                            "       u.unidad,\n" +
                            "       u.um\n" +
                            "from producto p, par_unidad u\n" +
                            "where p.sku = '"+Codigo+"' and\n" +
                            "      p.unidad = u.codigo;");

            if (Rs.next()){
            txCodigoProducto.setText(Rs.getString("sku"));
            txNombre.setText(Rs.getString("nombre").trim());
            txUnidad.setText(Rs.getString("unidad").trim());
            lbUM.setText(Rs.getString("um").trim());
            txCodigoCC.setText(Rs.getString("codigo_cc").trim());
            lbImagen.setText(Rs.getString("imagen").trim());
            } else {
                System.out.println("error");
            }
                    
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            Sql.Close();
        }
        
    }
    
     private boolean ExisteEnGrilla(String Codigo){
        for(int i=0; i< Grilla.getRowCount(); i++){
            if(Grilla.getValueAt(i,0).equals(Codigo)){
                Grilla.setRowSelectionInterval(i, 1);
                return true;
            }
        }
        return false;
    }
     
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btAbrirDoc;
    private javax.swing.JButton btAgregarProducto;
    private javax.swing.JButton btBuscarCodigo;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminaBulto1;
    private javax.swing.JButton btGenerarCatalogo;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbImagen;
    private javax.swing.JLabel lbUM;
    private javax.swing.JLabel lbUnidad;
    private javax.swing.JTextField txCodigoCC;
    private javax.swing.JTextField txCodigoProducto;
    private javax.swing.JTextField txIdCatalogo;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txPrecioOferta;
    private javax.swing.JTextField txPrecioReal;
    private javax.swing.JTextField txSubtitulo;
    private javax.swing.JTextField txTitulo;
    private javax.swing.JTextField txUnidad;
    // End of variables declaration//GEN-END:variables
}
