/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

import Conexion.ExeSql;
import Dialogos.jdBuscarCliPrv;
import static Dialogos.jdOC_PendientesFac.pano;
import static Dialogos.jdOC_PendientesFac.pmes;
import static Dialogos.jdOC_PendientesFac.pmes_oc;
import Dialogos.jdPagadoPrvCli;
import Dialogos.jdPagarPrv;
import Formularios.fmMain;
import static Formularios.fmMain.pnPestanas;
import Utilidades.Exporter;
import Utilidades.PanelTab;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author David Alcaman
 */
public class pfReporteVentasFinal extends javax.swing.JPanel {
    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
    /**
     * Creates new form pfReportePagosPrv
     */
    public pfReporteVentasFinal() {
        initComponents();
        CargaVendedor();
       // cbvenId.setVisible(false);
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
       /* int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);*/
        
        String anox ="x";
        String mesx ="x";
        
        anox = String.valueOf(año);
        mesx = String.valueOf(mes+1);

        cboAgno.setSelectedItem(anox); 
        cboMes.setSelectedItem(mesx); 
                
          
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        Grilla.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
        Grilla.getColumnModel().getColumn(8).setCellRenderer(rightRenderer);
        
        
        int intNivelMnu = 100;
        int intNivelUsuario = fmMain.trae_nivel(fmMain.GetUsuario());
        if (intNivelUsuario<100){
            btExcel.setVisible(false);
        }
        btExcel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbReg = new javax.swing.JLabel();
        lbSumMontos = new javax.swing.JLabel();
        btExcel = new javax.swing.JButton();
        lbTotalFAC = new javax.swing.JLabel();
        lbTotalFEC = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbTotalBOC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbVendedor = new javax.swing.JComboBox<String>();
        lblVendedor = new javax.swing.JLabel();
        cbvenId = new javax.swing.JComboBox<String>();
        btBuscar = new javax.swing.JButton();
        AGNO = new javax.swing.JPanel();
        cboAgno = new javax.swing.JComboBox<String>();
        cboMes = new javax.swing.JComboBox<String>();
        lblAgno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CboTipoDoc = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nro Registros:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FAC");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Pago Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("FEC");

        lbReg.setText("0.00");

        lbSumMontos.setText("0.00");

        btExcel.setText("Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });

        lbTotalFAC.setText("0.00");

        lbTotalFEC.setText("0.00");

        lblIva.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NCC");

        Grilla.setAutoCreateRowSorter(true);
        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Rut", "Cliente", "Tipo Docto", "Nro. Docto", "Afecto", "Exento", "Iva", "Total Docto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);
        if (Grilla.getColumnModel().getColumnCount() > 0) {
            Grilla.getColumnModel().getColumn(0).setMinWidth(110);
            Grilla.getColumnModel().getColumn(0).setPreferredWidth(110);
            Grilla.getColumnModel().getColumn(0).setMaxWidth(110);
            Grilla.getColumnModel().getColumn(1).setMinWidth(80);
            Grilla.getColumnModel().getColumn(1).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(1).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(2).setMinWidth(350);
            Grilla.getColumnModel().getColumn(2).setPreferredWidth(320);
            Grilla.getColumnModel().getColumn(2).setMaxWidth(350);
            Grilla.getColumnModel().getColumn(3).setMinWidth(80);
            Grilla.getColumnModel().getColumn(3).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(3).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(4).setMinWidth(100);
            Grilla.getColumnModel().getColumn(4).setPreferredWidth(100);
            Grilla.getColumnModel().getColumn(4).setMaxWidth(100);
            Grilla.getColumnModel().getColumn(5).setMinWidth(85);
            Grilla.getColumnModel().getColumn(5).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(5).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(6).setMinWidth(85);
            Grilla.getColumnModel().getColumn(6).setPreferredWidth(85);
            Grilla.getColumnModel().getColumn(6).setMaxWidth(85);
            Grilla.getColumnModel().getColumn(7).setMinWidth(80);
            Grilla.getColumnModel().getColumn(7).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(7).setMaxWidth(80);
            Grilla.getColumnModel().getColumn(8).setMinWidth(80);
            Grilla.getColumnModel().getColumn(8).setPreferredWidth(80);
            Grilla.getColumnModel().getColumn(8).setMaxWidth(80);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("BOC");
        jLabel7.setToolTipText("");

        lbTotalBOC.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lbReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalBOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalFAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalFEC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSumMontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(107, 107, 107)
                        .addComponent(btExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbReg)
                                .addComponent(jLabel7)
                                .addComponent(lbTotalBOC))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(lbSumMontos)
                                .addComponent(lblIva)
                                .addComponent(jLabel6)
                                .addComponent(lbTotalFEC)
                                .addComponent(jLabel5)
                                .addComponent(lbTotalFAC)
                                .addComponent(jLabel3)))
                        .addGap(10, 10, 10))
                    .addComponent(btExcel))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "VENDEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>" }));
        cbVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVendedorActionPerformed(evt);
            }
        });

        lblVendedor.setText("Vendedor:");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbvenId, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendedor)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbvenId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btBuscar)
                .addContainerGap())
        );

        AGNO.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PERIODO VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cboAgno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        cboAgno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAgnoActionPerformed(evt);
            }
        });

        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        lblAgno.setText("AÑO:");

        jLabel8.setText("MES:");

        CboTipoDoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Todos>", "BOC", "FAC", "FEC", "FMC", "NCC", "NDC" }));
        CboTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTipoDocActionPerformed(evt);
            }
        });

        jLabel9.setText("TIPO DOC:");

        javax.swing.GroupLayout AGNOLayout = new javax.swing.GroupLayout(AGNO);
        AGNO.setLayout(AGNOLayout);
        AGNOLayout.setHorizontalGroup(
            AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGNOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AGNOLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AGNOLayout.createSequentialGroup()
                        .addComponent(lblAgno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AGNOLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(CboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AGNOLayout.setVerticalGroup(
            AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGNOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgno)
                    .addComponent(cboAgno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AGNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CboTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AGNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AGNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jPanel3.getAccessibleContext().setAccessibleName("VENDEDOR");
        jPanel3.getAccessibleContext().setAccessibleDescription("");
        AGNO.getAccessibleContext().setAccessibleName("PERIODO VENCIMIENTO1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void CargaVendedor(){
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        cbVendedor.removeAllItems();
        cbvenId.removeAllItems();
        cbVendedor.addItem("<Todos>");  // Agrego la condicion inicial de Todos
        cbvenId.addItem("<Todos>");  // Agrego la condicion inicial de Todos
        try {
            Rs = Sql.Select("select LOWER(p.usuario) as user, p.vendedor || '-' || \n" +
                            "p.nombre || ' ' ||  p.apellidopaterno   || ' ' || p.apellidomaterno as nombre \n" +
                            "from personal p \n" +
                            "where p.vendedor >0 and empresa = 2 and activo is true");
            if(Sql.GetRowCount()==0) return;
     
           while(Rs.next()){
          
            cbVendedor.addItem( Rs.getString("nombre").trim());

            cbvenId.addItem(Rs.getString("user").trim());   
            //btBuscar.doClick();
           }        
           
           //cbVendedor.setSelectedIndex(-1);

           
           
        } catch (Exception e) {
            System.out.println(e);
        }
        finally{
            Sql.Close();
        }
    }
    
    
 
    
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        ExeSql Sql = new ExeSql();
        ResultSet Rs;
        String Query="";
        String NombrePersonal;
        String Str_totNC="";
        DefaultTableModel TableModel = (DefaultTableModel) Grilla.getModel();
        int ContPagos=0;
        double totNC=0.0;
            BigInteger TotalAfecto    = new BigInteger("0");
            BigInteger TotalBoleta    = new BigInteger("0");
            BigInteger TotalExento    = new BigInteger("0");
            BigInteger TotalNCC       = new BigInteger("0");
            BigInteger TotalIva       = new BigInteger("0");
            BigInteger Total          = new BigInteger("0");
  
        while(TableModel.getRowCount()>0)
           TableModel.removeRow(0);        
try {
                       
Query = "Select c.femision,case when cli.rut is null then 0 else cli.rut end, \n" +
        "case when cli.nombre is null then '' else cli.nombre end,c.tipdocto, p.apellidopaterno || ' ' || p.nombre as Vendedor,\n" +
        " c.nrodocto, \n" +
        "SUM(c.totalafecto )totalafecto,SUM(c.totalexento)totalexento,SUM(c.totaliva)totaliva,SUM(c.totaldocto) totaldocto, \n" +
        "SUM(c.totalafecto + c.totalexento) totNC " +        
        " from ctactecli c\n" +
        " left join occh oc on c.rut=oc.rut and c.codigo_oc=oc.codigo_oc and c.occh=oc.orden\n" +
        " left join cliente cli on cli.rut=c.rut\n" +
        " left join personal p on oc.vendedor=p.vendedor\n"+  
        " where extract(year from c.femision)= " + cboAgno.getSelectedItem().toString() + "\n" +
        " and extract(month from c.femision)=" + cboMes.getSelectedItem().toString() + "\n";
        
 if(CboTipoDoc.getSelectedIndex() >0){
    
     Query = Query +   " and c.tipdocto in ('" + CboTipoDoc.getSelectedItem().toString() + "') \n";  
 
 }else{
   
     Query = Query +   " and c.tipdocto in ('BOC','FAC','FEC','NCC') \n";  
 }

 if(cbVendedor.getSelectedIndex() >0){

    String nombrePalabra =cbVendedor.getSelectedItem().toString();
    int j =0;
      for(int i=0; i <nombrePalabra.length(); i++ ){
        
          if( nombrePalabra.charAt(i)== '-'){
          
              j=i;
             break;
          
          }
      }     
     
     
  
    Query = Query +   " and c.usuario in ('"+cbvenId.getSelectedItem()+"') \n";  
    //Query = Query +   " and oc.vendedor in (" + nombrePalabra.substring(0,j).trim() + ") \n";  
 }
 
 Query = Query + " Group by c.femision,cli.rut,cli.nombre,c.tipdocto, c.nrodocto,p.apellidopaterno || ' ' || p.nombre";
 // EJECUTA CONSULTA
            Rs = Sql.Select(Query);
            //long totalNC= 0;
            while(Rs.next()){
                ContPagos++;
              TableModel.addRow(new Object[]{Rs.getString("femision").trim(), 
                                               Rs.getString("rut").trim(), 
                                               Rs.getString("nombre").trim(),
                                               Rs.getString("tipdocto").trim(),
                                               Rs.getDouble("nrodocto"), 
                                              fmMain.SetGuardarEntero(Rs.getString("totalafecto")),
                                               fmMain.SetGuardarEntero(Rs.getString("totalexento")),
                                               fmMain.SetGuardarEntero(Rs.getString("totaliva")),
                                               fmMain.SetGuardarEntero(Rs.getString("totaldocto"))});
//                                               fmMain.FormatoTotal(Rs.getDouble("nrodocto")), 
//                                               fmMain.FormatoTotal(Rs.getDouble("totalafecto")),
//                                               fmMain.FormatoTotal(Rs.getDouble("totalexento")),
//                                               fmMain.FormatoTotal(Rs.getDouble("totaliva")),
//                                               fmMain.FormatoTotal(Rs.getDouble("totaldocto"))});
              
                 if (CboTipoDoc.getSelectedIndex() ==0){
                        if ( "BOC".equals(Rs.getString("tipdocto"))){
                            
                            TotalBoleta = TotalBoleta.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        
                        }else if ( "FAC".equals(Rs.getString("tipdocto"))){
                             
                            TotalAfecto = TotalAfecto.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        
                        }else if ( "NCC".equals(Rs.getString("tipdocto"))){
                            
                            TotalNCC = TotalNCC.add(new BigInteger(Rs.getString("totNC")));
                            
                        }   
                        if ( "FEC".equals(Rs.getString("tipdocto"))){
                             TotalExento = TotalExento.add(new BigInteger(Rs.getString("totalexento"))) ;
                         }
                        
                        
           }     
                 else  if (CboTipoDoc.getSelectedIndex() >0) {
                        TotalAfecto = TotalAfecto.add(new BigInteger(Rs.getString("totalafecto"))) ;
                        TotalExento = TotalExento.add(new BigInteger(Rs.getString("totalexento"))) ;
                        TotalIva    = TotalIva.add(new BigInteger(Rs.getString("totaliva"))) ;
                        Total       = Total.add(new BigInteger(Rs.getString("totaldocto"))) ;  
            }     
       }
            
            
            
            
            if (CboTipoDoc.getSelectedIndex() >0){
                        lbTotalBOC.setText(fmMain.FormatoNumeroBig(TotalBoleta));
                        lbTotalFAC.setText(fmMain.FormatoNumeroBig(TotalAfecto));
                        lbTotalFEC.setText(fmMain.FormatoNumeroBig(TotalExento));
                        lblIva.setText(fmMain.FormatoNumeroBig(TotalIva));
                        lbSumMontos.setText(fmMain.FormatoNumeroBig(Total));
            }
            else  if (CboTipoDoc.getSelectedIndex() ==0){  
                        lbTotalBOC.setText(fmMain.FormatoNumeroBig(TotalBoleta));
                        lbTotalFAC.setText(fmMain.FormatoNumeroBig(TotalAfecto));
                        lbTotalFEC.setText(fmMain.FormatoNumeroBig(TotalExento));
                        lblIva.setText(fmMain.FormatoNumeroBig(TotalNCC));
                        
                        Total = Total.add(TotalBoleta);
                        Total = Total.add(TotalAfecto);
                        Total = Total.add(TotalExento);
                        Total = Total.subtract(TotalNCC);
                        lbSumMontos.setText(fmMain.FormatoNumeroBig(Total));
                   
                       }
            
            
            lbReg.setText(fmMain.FormatoTotal(ContPagos));
            
    }
    catch (SQLException e) {
        
        Logger.getLogger(pfReporteVentasFinal.class.getName()).log(Level.SEVERE, null, e);
        fmMain.Mensaje("Existe una inconsistencia en la información.");
            
        }finally{
            Sql.Close();
        }
            
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        if(evt.getClickCount()==2 && !Grilla.getValueAt(Grilla.getSelectedRow(),0).toString().equals("Pendiente")){
            jdPagadoPrvCli Pagado = new jdPagadoPrvCli(null, true);
            Pagado.setLocationRelativeTo(null);
            Pagado.setTitle("Pagos Realizados");
            Pagado.CargaPagosPrv(Grilla.getValueAt(Grilla.getSelectedRow(), 12).toString().trim(),"");  
            Pagado.setVisible(true);
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed
//        if(Grilla.getRowCount()==0){
//            fmMain.Mensaje("Nada que exportar");
//            return;
//        }
//        
//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo Excel",".xls");
//        chooser.setFileFilter(filter);
//        chooser.setDialogTitle("Guardar Informe en Excel");
//        chooser.setMultiSelectionEnabled(false);
//        chooser.setAcceptAllFileFilterUsed(false);
//        
//        if(chooser.showSaveDialog(null)== JFileChooser.APPROVE_OPTION){
//            List<JTable> tb=new ArrayList<>();
//            List<String> nom=new ArrayList<>();
//            tb.add(Grilla);
//            nom.add("Ventas");
//            String file=chooser.getSelectedFile().toString().concat(".xls");
//            try {
//                Exporter e = new Exporter(new File(file), tb, nom);
//                if(e.export())
//                    fmMain.Mensaje("Datos Exportados");
//            } catch (Exception e) {
//                fmMain.Mensaje(e.getMessage());
//            }
//            
//            
//        }
        
   if(Grilla.getRowCount()==0){
            fmMain.Mensaje("Nada que exportar");
            return;
        }

            List<JTable> tb=new ArrayList<>();
            List<String> nom=new ArrayList<>();
            tb.add(Grilla);
            nom.add("Ventas");
            
            File folder = new File("c:/temp");
            if (!folder.exists())
            {
                folder.mkdir();
            }
            
             String file = "C:/temp/Ventas.xls";       
            
            
            try {
                Exporter e = new Exporter(new File(file), tb, nom);
                
                if(e.export())
                //fmMain.Mensaje("Datos Exportados");
                abrir(file);
                
            } catch (Exception e) {
                fmMain.Mensaje(e.getMessage());
            }        
        
    }//GEN-LAST:event_btExcelActionPerformed

        public void abrir(String file ){
        
       try {
           String url = file;
           ProcessBuilder p = new ProcessBuilder();
           p.command("cmd.exe", "/c",url);
           p.start();
       } catch (IOException ex) {
           Logger.getLogger(pfReporteVentasFinal.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
    private void cbVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVendedorActionPerformed
         
       
        
        
        if (cbVendedor.getSelectedIndex() > 0){
        
            System.out.println("EL INDICE ES : "+cbVendedor.getSelectedIndex());
            
            int indice = cbVendedor.getSelectedIndex();
            
            cbvenId.setSelectedIndex(indice);
        }

        
    }//GEN-LAST:event_cbVendedorActionPerformed

    private void CboTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTipoDocActionPerformed
      if (CboTipoDoc.getSelectedIndex() >0){
             jLabel6.setText("IVA"); 
       }  
       else{
           jLabel6.setText("NCC");
            }  
      //btBuscar.doClick();
    }//GEN-LAST:event_CboTipoDocActionPerformed

    private void cboAgnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAgnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAgnoActionPerformed
//6700

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AGNO;
    private javax.swing.JComboBox<String> CboTipoDoc;
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JComboBox<String> cboAgno;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JComboBox<String> cbvenId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lbReg;
    private javax.swing.JLabel lbSumMontos;
    private javax.swing.JLabel lbTotalBOC;
    private javax.swing.JLabel lbTotalFAC;
    private javax.swing.JLabel lbTotalFEC;
    private javax.swing.JLabel lblAgno;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblVendedor;
    // End of variables declaration//GEN-END:variables
}
