/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelForm;

/**
 *
 * @author luvaly
 */
import Conexion.ExeSql;
import Dialogos.jdVoucher;
import Formularios.fmMain;
import static Formularios.fmMain.IntPosicionFinal; 
import Utilidades.Ftp;
import Utilidades.SubeFTP;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.security.Principal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Icon;
import javax.swing.JFileChooser;



public class voucher extends javax.swing.JPanel {

    /**
     * Creates new form voucher
     */
    public int guardo=0;
    Image img;
    public String Tipo, Numero, Voucher, Trans;
    public int cod_transp;
    public voucher() 
    {
    
        initComponents();
     
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        bt_ArchivaImg = new javax.swing.JButton();
        btVerPdf = new javax.swing.JButton();

        jMenuItem2.setText("Pegar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);
        jMenuItem2.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jMenuItem1.setText("Guargar Imagen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleParent(jPopupMenu1);

        jMenuItem3.setText("Copiar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("Inserte Imagen  Aquí.");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jLabel1.setComponentPopupMenu(jPopupMenu1);

        bt_ArchivaImg.setText("Archivar");
        bt_ArchivaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ArchivaImgActionPerformed(evt);
            }
        });

        btVerPdf.setText("Ver Archivo");
        btVerPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bt_ArchivaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVerPdf)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVerPdf)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bt_ArchivaImg)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         ExeSql Sql = new ExeSql();
         String qryInsAudito;
         String Query ="";
         
/*        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);*/
        
        
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");

System.out.println(date.format(now));
System.out.println(hour.format(now));
System.out.println(now);
        try {
                String ruta ="";
                String sistema = System.getProperty("os.name").toLowerCase();
                 File folder = new File("");
                   if (sistema.contains("win"))
                   {
                       ruta = "c:/fotos/";
                       folder = new File(ruta.substring(0,ruta.length()-1));
                   }
                   else{
                       ruta = "/fotos/";
                        folder = new File(ruta);
                   } 
            System.out.println("1- indica la ruta");
            System.out.println(ruta);
           
            System.out.println("2- pregunta Si la ruta Existe");
            if (!folder.exists())
            {
                folder.mkdir();
                System.out.println("3");
            }
            System.out.println("4-Indicamos Ruta - Directorio estaba creado");
            System.out.println(ruta+Trans+"_"+Voucher+"_"+Tipo+"_"+Numero+".png");
            File file = new File(ruta+Trans+"_"+Voucher+"_"+Tipo+"_"+Numero+".png");
            System.out.println("4-1 (");
            file.setReadable(true);
            System.out.println("4-2");
            ImageIO.write((RenderedImage) img, "png", file);
            System.out.println("5");
            
            
            //SubeFTP Sube = new SubeFTP();
            String laruta = ruta+Trans+"_"+Voucher+"_"+Tipo+"_"+Numero+".png";
            String rutafinal = Trans+"_"+Voucher+"_"+Tipo+"_"+Numero+".png";
            //CODIGO ACTIVAR ---------------------------------------------------------------------------
            SubeFTP.SubeArch(laruta, rutafinal);   
            Query = " update transporte_despachos set imagen_voucher = '\\\\\\\\192.168.0.130\\\\Voucher\\\\" + rutafinal + "' where tipdocto='" + Tipo + "' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" ;
            Sql.ExeSql(Query);
            //CODIGO ACTIVAR ---------------------------------------------------------------------------
            //SACAR
            //Sql.ExeSql("update transporte_despachos set imagen_voucher='C://fotos//"+rutafinal+"' where tipdocto='"+Tipo+"' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" );
            //SACAR
//            qryInsAudito= "  insert into auditoria_bd\n" +
//"            (usuario, fecha,  tabla,tipo_cambio,campo1,campo2,campo3,campo4,old_valor, new_valor)\n" +
//"            values\n" +
////"            ('" + fmMain.GetUsuario()   + "','transporte_despachos','Graba_Imagen','" + date.format(now) + ' ' + hour.format(now)  + "','" + rutafinal +"','" + Trans + "','" + Numero + "', '" + Tipo + "', null)";
//"            ('" +   fmMain.GetUsuario().toLowerCase()   + "' ,'" +  date.format(now) + ' ' + hour.format(now)  + "','transporte_despachos','Graba_Imagen','" + Voucher + "','" +  date.format(now) + ' ' + hour.format(now)  + "','" + rutafinal +"','" + Trans + "','" + Numero + "', '" + Tipo + "')";
            
            qryInsAudito= "  insert into auditoria_despachos\n" +
"            (usuario, fecha,  tipo_cambio,voucher,imagen,transporte,nrodocto, tipdocto)\n" +
"            values\n" +
"            ('" +   fmMain.GetUsuario().toLowerCase()   + "' ,'" +  date.format(now) + ' ' + hour.format(now)  + "','Graba_Imagen','" + Voucher + ",'" + rutafinal +"','" + Trans + "','" + Numero + "', '" + Tipo + "')";
            Sql.ExeSql(qryInsAudito);
            Sql.Commit();
            guardo=1;
            fmMain.Mensaje("Se ha guardado la imagen correctamente");
       
            
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            fmMain.Mensaje("Verifique que este creada la carpeta c:\\fotos\\ y que tenga conexion al servidor 130");
        } catch (SQLException ex) {
            Logger.getLogger(jdVoucher.class.getName()).log(Level.SEVERE, null, ex);
            Sql.Rollback();
        }
        finally{
            Sql.Close();
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          PegarImagen();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            
            Icon icon = jLabel1.getIcon();

                BufferedImage bi = new BufferedImage(
                    icon.getIconWidth(),
                    icon.getIconHeight(),
                    BufferedImage.TYPE_INT_RGB);
                Graphics g = bi.createGraphics();
                // paint the Icon to the BufferedImage.
                icon.paintIcon(null, g, 0,0);
                g.setColor(Color.WHITE);
                g.dispose();
            
            
            
             TransferableImage trans = new TransferableImage(bi);
           clipboard.setContents(trans, null);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    public void CargaPdf(int Transporte, String Voucher, String numero){
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        String server,user,pass,ruta_local="";
        int puerto =21;
         String rutaimage="";
          String rutrans="";
        try {

//            server= "192.168.0.130";
//            user="voucher";
//            pass="V2369";
            
            
           //trae datos ftp
            server="";
            puerto=0;
            user=""; 
            pass="";
            
            	Rs = Sql.Select("SELECT * from conexiones where tipo='ftp'");
                if (Rs.next())
                {
                    if(!fmMain.GetInternet()){
                        server = Rs.getString("serv");
                        user  = Rs.getString("usu");
                        puerto  = Rs.getInt("port");
                        pass = Rs.getString("pass");
                    }
                    else {
                        server = "186.67.157.227";
                        user  = Rs.getString("usu");
                        puerto  = 21;
                        pass = Rs.getString("pass");
                    }
                }
           //trae datos ftp
            
            Rs = Sql.Select("SELECT count(pdf_voucher) as hay from transporte_despachos where transporte = "+Transporte+" and nrodocto = "+numero+" and voucher='"+Voucher+"' and tipdocto = '"+Tipo+"'");
            Rs.next();
            if (Rs.getInt("hay")>=1)
            {
                if (Voucher.equals("")){
                    Voucher = Rs.getString("voucher");
                }                    
                Rs = Sql.Select("SELECT pdf_voucher as pdf from transporte_despachos where transporte ="+Transporte+" and nrodocto = "+numero+" and voucher = '" + Voucher + "' and tipdocto = '"+Tipo+"'");
                Rs.next();
                if (Rs.getString("pdf") != null)
                {

                    //Verifica SO
                    String sistema = System.getProperty("os.name").toLowerCase();
                    File folder = new File("");
                    if (sistema.contains("win"))
                    {
                         ruta_local = "c:/fotos2/";
                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
                    }
                    else{
                          ruta_local = "/fotos2/";
                          folder = new File(ruta_local);
                    }
                    if (!folder.exists())
                    {
                        folder.mkdir();
                    }
                    String archivo = "";
                    rutaimage=Rs.getString("pdf");
                    
                    
                    if (Rs.getString("pdf") != null)
                    {
                         archivo = fmMain.GetStringDeFinal('\\', rutaimage);
                         rutrans = rutaimage.substring(28,rutaimage.length()).trim();
                    }
//                            String rutrans="";
//                            if (Transporte == 1)
//                            {
//                                rutrans = "/tnt/";
//                                //archivo = rutaimage.substring(33,rutaimage.length());
//                                archivo = fmMain.GetStringDeFinal('\\', rutaimage);
//                            }
//                            else if (Transporte == 7)
//                            {
//                                rutrans = "/blue/";
//                                //archivo = rutaimage.substring(34,rutaimage.length());
//                                archivo = fmMain.GetStringDeFinal('\\', rutaimage);
//                            }
//                            else
//                                {
//                                rutrans = "/";
//                                archivo = fmMain.GetStringDeFinal('\\', rutaimage);
//                            }
                      
//                        rutrans = "/";
//                        archivo = fmMain.GetStringDeFinal('\\', rutaimage);
                    
//                    String  Archivo_buscado = Ftp.busca_archivoFTP(server, puerto, user, pass, ruta_local, "",archivo);
//                   if (Archivo_buscado.equals("") )
//                   {
                    Ftp.baja_archivo_ftp(server, puerto,user, pass,"/" + rutrans,ruta_local + archivo);
                    File file = new File(archivo);
                    File pathCompleto = new File(ruta_local + file);
                    Desktop.getDesktop().open(pathCompleto); 
//                   } 
//                   else
//                   {
//                       rutrans = "/";
//                       Ftp.baja_archivo_ftp(server, puerto,user, pass,rutrans+archivo,ruta_local + Archivo_buscado);
//                       File file = new File(archivo);
//                       File pathCompleto = new File(ruta_local + file);
//                       Desktop.getDesktop().open(pathCompleto); 
//                   }
                                      
                }
               
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        finally{
            Sql.Close();
            
        }
    }
    
    
    private void bt_ArchivaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ArchivaImgActionPerformed
        // TODO add your handling code here:
      ResultSet Rs;
      ExeSql Sql = new ExeSql();
       String server="";
      

        
         String ruta ="", Query ="";
          File f = new File("");
                String sistema = System.getProperty("os.name").toLowerCase();
                 
                   if (sistema.contains("win"))
                   {
                       ruta = "c:/fotos2/pdf/";
                        f = new File(ruta.substring(0,ruta.length()-1));
                   }
                   else{
                       ruta = "/fotos2/pdf/";
                       
                   } 
        
                    if(!f.isDirectory()) {
                    String newFolder = ruta; //cualquierCarpeta es el nombre de la Carpeta que vamos a crear
                    
                    File myNewFolder = new File(newFolder);
                    myNewFolder.mkdirs(); //creamos la carpeta
                   }
                    else
                   {
                          System.out.println("La carpeta ya estaba creada");
                   }
                    
                   
                   
            JFileChooser j=new JFileChooser();
            j.setFileSelectionMode(JFileChooser.FILES_ONLY);//solo archivos y no carpetas
            int estado=j.showOpenDialog(null);
            if(estado== JFileChooser.APPROVE_OPTION){
                //SubeFTP Sube = new SubeFTP();
            
            String laruta = String.valueOf(j.getSelectedFile());
            String rutafinal =  fmMain.GetStringDeFinal('\\', laruta);
            String[] sas = laruta.split("//");
            String path=j.getSelectedFile().getAbsolutePath();
            String filename=j.getSelectedFile().getName();
            
            System.out.println(filename);
            if (sistema.contains("win")){}
            else {
                rutafinal = filename;
            }
                try
                {
                    //trae datos ftp
                    server="";
            
                    Rs = Sql.Select("SELECT * from conexiones where tipo='ftp'");
                        if (Rs.next())
                        {
                            server = Rs.getString("serv");
                        }
      
                    
            //Sube Archivo FTP ---------------------------------------------------------------------------
                String conection = String.valueOf(laruta);  
//                System.out.println(String.valueOf("RUTAAAAAA: "+ruta));
                SubeFTP.SubeArch_con(laruta, rutafinal, cod_transp);  
                JOptionPane.showMessageDialog(null, "Archivo subido con éxito.");
                //Se filta el tipo de documento y se modifica la consulta según el tipo
                if(cod_transp==1){//Filtro según tipo transporte. Ricardo Ortiz
                    Query = " update transporte_despachos set imagen_voucher = null \n" +
                        " , pdf_voucher = '\\\\\\\\" + server + "\\\\Voucher\\\\tnt\\\\" + rutafinal + "' \n" +
                        " where tipdocto='" + Tipo + "' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" ;
                    Sql.ExeSql(Query);
                }
                else if(cod_transp==7){
                    Query = " update transporte_despachos set imagen_voucher = null \n" +
                        " , pdf_voucher = '\\\\\\\\" + server + "\\\\Voucher\\\\blue\\\\" + rutafinal + "' \n" +
                        " where tipdocto='" + Tipo + "' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" ;
                    Sql.ExeSql(Query);
                }
                else{
                    Query = " update transporte_despachos set imagen_voucher = null \n" +
                        " , pdf_voucher = '\\\\\\\\" + server + "\\\\Voucher\\\\" + rutafinal + "' \n" +
                        " where tipdocto='" + Tipo + "' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" ;
                    Sql.ExeSql(Query);
                }
//                Query = " update transporte_despachos set imagen_voucher = '\\\\\\\\192.168.0.130\\\\Voucher\\\\" + rutafinal + "' \n" +
//                        " , pdf_voucher = '\\\\\\\\192.168.0.130\\\\Voucher\\\\" + rutafinal + "' \n" +
//                        " where tipdocto='" + Tipo + "' and nrodocto="+ Numero + " and voucher ='" + Voucher + "'" ;
                Sql.Commit();
           //Sube Archivo FTP ---------------------------------------------------------------------------
                }
               catch (Exception e) 
               {
                   Sql.Rollback();
                   JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
               }
               finally
               {
                   Sql.Close();
               }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_bt_ArchivaImgActionPerformed

    private void btVerPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerPdfActionPerformed
        // TODO add your handling code here:
    
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        int transporte=-1;
        boolean valida = false;
try
{
            Rs = Sql.Select("SELECT transporte from transporte_despachos where nrodocto ="+ Numero + " and voucher='"+Voucher+"' and tipdocto = '"+Tipo+"'");
            if (Rs.next())
            {    
                transporte = Rs.getInt("transporte");
            }
            
            Rs = Sql.Select("SELECT codigo from par_general where tipo = 'TRANSPORTE'");
            if (Rs.next())
            {
                valida = true;
            }
            else
            {
                valida = false;
            }    
            
            
}       
  catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        finally{
            Sql.Close();
            
        }       
        
        if (valida)
        {
            System.out.println("Encontrado");
            CargaPdf(transporte, Voucher,Numero);
        }    
        else
            {
            fmMain.Mensaje("Existe un problema en la recuperación del transporte");
            }
    }//GEN-LAST:event_btVerPdfActionPerformed

    
       private void formKeyReleased(java.awt.event.KeyEvent evt) {                                 
        
    }                                
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
        if ((evt.getKeyCode() == KeyEvent.VK_V) && ((evt.getModifiers() & KeyEvent.CTRL_MASK) != 0)) {
            PegarImagen();
        }
    }                               
    
   public void limpiar_clip(){ 
    String comando ="cmd /c \"echo off| clip\"";
            try{
          
            Runtime. getRuntime(). exec(comando);
            System. out. println(comando);
            }catch(Exception ex){
            System. out. println("Ha ocurrido un error al ejecutar el comando. Error: "+ex);
            }
}  

    public void PegarImagen()
    {
        System.out.println("copio");
        
        try {
            //pasteString = (String)(CLIPBOARD.getContents(this).getTransferData(DataFlavor.stringFlavor));
            getImageFromClipboard();
//            ImageIcon foto =  new ImageIcon(img);
//            jLabel1.setIcon(foto);
//            jLabel1.setText("");
//            guardo=0;
            
            
              
                    Image scaledInstance = img.getScaledInstance(950  , 633, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(scaledInstance));
                    jLabel1.setText("");
                    guardo=0;
                    
                    
                   
            
            
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo invalido intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }
    
                                      
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        
    }                                 
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
      
        
    }                                  
    
                                       

   
    
    public Image getImageFromClipboard()
            throws Exception
    {
        Transferable transferable = Toolkit.getDefaultToolkit().getSystemClipboard().getContents(null);
        if (transferable != null && transferable.isDataFlavorSupported(DataFlavor.imageFlavor))
        {
            img = (Image) transferable.getTransferData(DataFlavor.imageFlavor);
            //Imagen Imagen = new Imagen();
            //jLabel1.setIcon(img);
            return img;
        }
        else
        {
            return null;
        }
    }
    
    public void CargaImagen(String Tipo, String Numero, String Voucher){
        ResultSet Rs;
        ExeSql Sql = new ExeSql();
        String server,user,pass,ruta_local="";
        int puerto =21;
         String rutaimage="";
        try {

//            server= "192.168.0.130";
//            user="voucher";
//            pass="V2369";
            
            
           //trae datos ftp
            server="";
            puerto=0;
            user=""; 
            pass="";
            	Rs = Sql.Select("SELECT * from conexiones where tipo='ftp'");
                if (Rs.next())
                {
                    if(!fmMain.GetInternet()){
                        server = Rs.getString("serv");
                        user  = Rs.getString("usu");
                        puerto  = Rs.getInt("port");
                        pass = Rs.getString("pass");
                    }
                    else {
                        server = "186.67.157.227";
                        user  = Rs.getString("usu");
                        puerto  = 21;
                        pass = Rs.getString("pass");
                    }
                }
           //trae datos ftp
            
            Rs = Sql.Select("SELECT count(imagen_voucher) as hay from transporte_despachos where tipdocto='"+Tipo+"' and nrodocto="+Numero);
            Rs.next();
            if (Rs.getInt("hay")>=1)
            {
                if (Voucher.equals("")){
                    Voucher = Rs.getString("voucher");
                }                    
                Rs = Sql.Select("SELECT imagen_voucher as imagen, pdf_voucher as pdf, transporte from transporte_despachos where tipdocto='"+Tipo+"' and nrodocto="+Numero + " and voucher = '" + Voucher + "'");
                Rs.next();
                if (Rs.getString("imagen") != null)
                {

                    //Verifica SO
                    String sistema = System.getProperty("os.name").toLowerCase();
                    File folder = new File("");
                    if (sistema.contains("win"))
                    {
                         ruta_local = "c:/fotos2/";
                         folder = new File(ruta_local.substring(0,ruta_local.length()-1));
                    }
                    else{
                          ruta_local = "/fotos2/";
                          folder = new File(ruta_local);
                    }
                    if (!folder.exists())
                    {
                        folder.mkdir();
                    }
                    
                    
                    
                    
                    
                    
                    
                    rutaimage=Rs.getString("imagen");
                    String archivo_remoto = rutaimage.substring(28,rutaimage.length());
                    String archivo = fmMain.GetStringDeFinal('\\', rutaimage);
                    Ftp.baja_archivo_ftp(server, puerto,user, pass,"/"+archivo_remoto,ruta_local + archivo);
                    
                    System.out.println("Remoto: "+ archivo_remoto);
                     File file = new File(ruta_local+archivo);
                     BufferedImage read = ImageIO.read(file);
                    
                    /* Estaba antes del cambio 14/06/2017
                        File file = new File(rutaimage);
                        BufferedImage read = ImageIO.read(file);
                    */
                    //File file = new File(Rs.getString("imagen"));
                    //BufferedImage read = ImageIO.read(file);
                    
                    Image scaledInstance = read.getScaledInstance(950  , 633, Image.SCALE_DEFAULT);
                    jLabel1.setIcon(new ImageIcon(scaledInstance));
                    jLabel1.setText("");
                    
                }
               
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        finally{
            Sql.Close();
            
        }
    }
    
    private class TransferableImage implements Transferable {

        Image i;

        public TransferableImage( Image i ) {
            this.i = i;
        }

        @Override
        public Object getTransferData( DataFlavor flavor )
        throws UnsupportedFlavorException, IOException {
            if ( flavor.equals( DataFlavor.imageFlavor ) && i != null ) {
                return i;
            }
            else {
                throw new UnsupportedFlavorException( flavor );
            }
        }

        public DataFlavor[] getTransferDataFlavors() {
            DataFlavor[] flavors = new DataFlavor[ 1 ];
            flavors[ 0 ] = DataFlavor.imageFlavor;
            return flavors;
        }

        public boolean isDataFlavorSupported( DataFlavor flavor ) {
            DataFlavor[] flavors = getTransferDataFlavors();
            for ( int i = 0; i < flavors.length; i++ ) {
                if ( flavor.equals( flavors[ i ] ) ) {
                    return true;
                }
            }

            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerPdf;
    private javax.swing.JButton bt_ArchivaImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}



